package
{	
	/**
	 * t: "tile",
	 * f: "tile_violet", 
	 * o: "tile_white", 
	 * j: "tile_orange",
	 * x: "exit", 
	 * w: "weaktile", 
	 * s: "splitter",
	 * e: "easyswitch", 
	 * h: "hardswitch",
	 * 
	 * Turn bridges off.
	 * l: "left", 
	 * r: "right", 
	 * u: "up", 
	 * d: "down", 
	 * 
	 * Turn bridges on.
	 * v: "left", 
	 * b: "right", 
	 * n: "up", 
	 * m: "down"
	 * @author Alexey Kuznetsov
	 */
	public class Levels
	{
		public static const EMPTY_CELL:String = " ";
		public static const REGULAR_CELL:String = "t";
		public static const EXIT_CELL:String = "x";
		public static const REGULAR_WHITE_CELL:String = "o";
		public static const REGULAR_PURPLE_CELL:String = "f";
		public static const REGULAR_ORANGE_CELL:String = "j";
		public static const WEAK_TILE:String = "w";
		public static const SPLITTER_TILE:String = "s";
		public static const EASY_SWITCH_TILE:String = "e";
		public static const HARD_SWITCH_TILE:String = "h";

		public static const BRIDGE_RIGHT:String = "r";
		public static const BRIDGE_LEFT:String = "l";
		public static const BRIDGE_UP:String = "u";
		public static const BRIDGE_DOWN:String = "d";

		//Bridges with power
		public static const BRIDGE_RIGHT_P:String = "b";
		public static const BRIDGE_LEFT_P:String = "v";
		public static const BRIDGE_UP_P:String = "n";
		public static const BRIDGE_DOWN_P:String = "m";

		private static var levels:Array;
		
		public static function getLevel(id:int):Array
		{
			if (!levels) createLevels();
			return levels[id];
		}
		
		private static function createLevels():void
		{
			levels = [];
			
			for (var n:uint = 1; n < 102; n++)
			{
				levels[n] = new Array();
			}
			
			levels[1].push("               ");
			levels[1].push("               ");
			levels[1].push("               ");
			levels[1].push("               ");
			levels[1].push("               ");
			levels[1].push("          t    ");
			levels[1].push("    tttt txt   ");
			levels[1].push("    t  t  t    ");
			levels[1].push("    t  t  t    ");
			levels[1].push("    t  tttt    ");
			levels[1].push("               ");
			levels[1].push("               ");
			levels[1].push("               ");
			levels[1].push("               ");
			levels[1].push("               ");
			levels[1].push([4, 9]);
			
			levels[2].push("               ");
			levels[2].push("               ");
			levels[2].push("               ");
			levels[2].push("               ");
			levels[2].push("   ttttttt     ");
			levels[2].push("   t     t     ");
			levels[2].push("   t     t     ");
			levels[2].push("   t  tttt     ");
			levels[2].push("   t  t        ");
			levels[2].push("   t  t    ttt ");
			levels[2].push("tttt  ttttttxt ");
			levels[2].push("           ttt ");
			levels[2].push("               ");
			levels[2].push("               ");
			levels[2].push("               ");
			levels[2].push([0, 10]);
			
			levels[3].push("               ");
			levels[3].push("               ");
			levels[3].push("               ");
			levels[3].push("               ");
			levels[3].push("               ");
			levels[3].push("    tttt       ");
			levels[3].push("ttttt  ttttt   ");
			levels[3].push("ttttt  tttttt  ");
			levels[3].push("t         txt  ");
			levels[3].push("          ttt  ");
			levels[3].push("               ");
			levels[3].push("               ");
			levels[3].push("               ");
			levels[3].push("               ");			
			levels[3].push("               ");
			levels[3].push([0, 8]);
			
			levels[4].push("               ");
			levels[4].push("               ");
			levels[4].push("               ");
			levels[4].push("               ");
			levels[4].push("        ttt    ");
			levels[4].push("        txt    ");
			levels[4].push("      tttt     ");
			levels[4].push("      tttt     ");
			levels[4].push("      t        ");
			levels[4].push("   tttt        ");
			levels[4].push("   tttt        ");
			levels[4].push("   t           ");
			levels[4].push("               ");
			levels[4].push("               ");
			levels[4].push("               ");
			levels[4].push([3, 11]);
			
			levels[5].push("               ");
			levels[5].push("               ");
			levels[5].push("               ");
			levels[5].push("               ");
			levels[5].push("     ttt       ");
			levels[5].push("     ttt       ");
			levels[5].push("     t ttt     ");
			levels[5].push("        tt     ");
			levels[5].push("       ttt     ");
			levels[5].push("     ttt       ");
			levels[5].push("    tttt       ");
			levels[5].push("    txt        ");
			levels[5].push("    ttt        ");
			levels[5].push("               ");
			levels[5].push("               ");
			levels[5].push([5, 6]);
			
			levels[6].push("               ");
			levels[6].push("               ");
			levels[6].push("               ");
			levels[6].push("               ");
			levels[6].push(" ttttttttt     ");
			levels[6].push(" ttt     t     ");
			levels[6].push("   t     t     ");
			levels[6].push("   t    ttt    ");
			levels[6].push("   t    txttt  ");
			levels[6].push("   t    ttt t  ");
			levels[6].push(" ttt        t  ");
			levels[6].push(" tttttttttttt  ");
			levels[6].push("               ");
			levels[6].push("               ");
			levels[6].push("               ");
			levels[6].push([3, 7]);
			
			levels[7].push("               ");
			levels[7].push("               ");
			levels[7].push("               ");
			levels[7].push("      ttttttt  ");
			levels[7].push("      t     t  ");
			levels[7].push("      t     t  ");
			levels[7].push("      t ttttt  ");
			levels[7].push("      t t   t  ");
			levels[7].push("      t t  ttt ");
			levels[7].push("ttttttt t  txt ");
			levels[7].push("t       tt ttt ");
			levels[7].push("t       tt     ");
			levels[7].push("tttttttttt     ");
			levels[7].push("               ");
			levels[7].push("               ");
			levels[7].push([3, 12]);
			
			levels[8].push("               ");
			levels[8].push("       t       ");
			levels[8].push("      ttt      ");
			levels[8].push("      ttt      ");
			levels[8].push("    ttt ttt    ");
			levels[8].push("   ttt   ttt   ");
			levels[8].push("    ttt ttt    ");
			levels[8].push("      t t      ");
			levels[8].push("      t t      ");
			levels[8].push("   tttt tttt   ");
			levels[8].push("  tt       tt  ");
			levels[8].push("  tt   ttt tt  ");
			levels[8].push("   tttttxttt   ");
			levels[8].push("       ttt     ");
			levels[8].push("               ");
			levels[8].push([7, 1]);
			
			levels[9].push("               ");
			levels[9].push("            t  ");
			levels[9].push("            t  ");
			levels[9].push("            t  ");
			levels[9].push("         tttt  ");
			levels[9].push("         t  t  ");
			levels[9].push("         t  t  ");
			levels[9].push("      ttttttt  ");
			levels[9].push("      t  t  t  ");
			levels[9].push("      t  t  t  ");
			levels[9].push("      ttttttt  ");
			levels[9].push("      t  t  t  ");
			levels[9].push("  ttt t  t  t  ");
			levels[9].push("  txttttttttt  ");
			levels[9].push("  ttt          ");
			levels[9].push([12, 1]);
			
			levels[10].push("               ");
			levels[10].push("               ");
			levels[10].push("               ");
			levels[10].push("               ");
			levels[10].push("  ttttttt      ");
			levels[10].push("  t     t      ");
			levels[10].push("  t     t   ttt");
			levels[10].push("tttt   ttttttxt");
			levels[10].push("t tt   tt   ttt");
			levels[10].push("t tt   tt      ");
			levels[10].push("t              ");
			levels[10].push("               ");
			levels[10].push("               ");
			levels[10].push("               ");
			levels[10].push("               ");
			levels[10].push([0, 10]);
			
			levels[11].push("               ");
			levels[11].push("           ttt ");
			levels[11].push("           txt ");
			levels[11].push("  tt       ttt ");
			levels[11].push("  tt        t  ");
			levels[11].push(" tttttt     t  ");
			levels[11].push("    ttt     t  ");
			levels[11].push("    ttt   ttt  ");
			levels[11].push("  ttt     ttt  ");
			levels[11].push("  ttt tt    t  ");
			levels[11].push("    t tt  ttt  ");
			levels[11].push("    tttt ttt   ");
			levels[11].push("      t  t     ");
			levels[11].push("      t  t     ");
			levels[11].push("      tttt     ");
			levels[11].push([1, 5]);
			
			levels[12].push("               ");
			levels[12].push("ttt ttt        ");
			levels[12].push("tt  ttt        ");
			levels[12].push("ttttttt        ");
			levels[12].push("    t t ttt ttt");
			levels[12].push("ttttttt tttttxt");
			levels[12].push("t   ttt   t ttt");
			levels[12].push("t       ttt    ");
			levels[12].push("ttt     tt     ");
			levels[12].push("ttt tttttt     ");
			levels[12].push("t  tt          ");
			levels[12].push("t  tt          ");
			levels[12].push("tttttt         ");
			levels[12].push("   ttt         ");
			levels[12].push("               ");
			levels[12].push([2, 1]);

			levels[13].push("            ttt");
			levels[13].push("  ttt       ttt");
			levels[13].push("tttxtttt    ttt");
			levels[13].push("t ttt tt     t ");
			levels[13].push("t     tt     t ");
			levels[13].push("t     tttttt t ");
			levels[13].push("tttt       t t ");
			levels[13].push("tttt       t t ");
			levels[13].push("   t    tttt t ");
			levels[13].push("   t    t  t t ");
			levels[13].push("   t    t  t t ");
			levels[13].push("   t    t  t t ");
			levels[13].push("   ttt  t tt t ");
			levels[13].push("   ttt  t tttt ");
			levels[13].push("     tttt ttt  ");
			levels[13].push([13, 1]);
			
			levels[14].push("               ");
			levels[14].push("tttttttttttttt ");
			levels[14].push("ttt tt       tt");
			levels[14].push("  t tt       tt");
			levels[14].push("  t   tttt  ttt");
			levels[14].push("  t   t  t ttt ");
			levels[14].push(" ttt ttt t t   ");
			levels[14].push(" ttt txt t t   ");
			levels[14].push(" ttt ttt t tttt");
			levels[14].push("  t      t   tt");
			levels[14].push("  t      ttt tt");
			levels[14].push("  tttttttttt t ");
			levels[14].push("  tt           ");
			levels[14].push("  tt           ");
			levels[14].push("               ");
			levels[14].push([13, 11]);
			
			levels[15].push("               ");
			levels[15].push(" ttttttttttttt ");
			levels[15].push(" t       t  tt ");
			levels[15].push(" t       t  tt ");
			levels[15].push(" t  tttt t     ");
			levels[15].push(" tt t  t tt    ");
			levels[15].push(" tt t  t tt    ");
			levels[15].push("  t t  t  t    ");
			levels[15].push("ttt tt t  t    ");
			levels[15].push("ttt tt t  t    ");
			levels[15].push("t  ttt tttt    ");
			levels[15].push("t  ttt         ");
			levels[15].push("t  t   tt   ttt");
			levels[15].push("ttttt  tt  ttxt");
			levels[15].push("ttttttttttttttt");
			levels[15].push([7, 7]);
			
			levels[16].push("               ");
			levels[16].push("               ");
			levels[16].push("               ");
			levels[16].push("       wwwww   ");
			levels[16].push("   ttt wwwww   ");
			levels[16].push("   txttt   t   ");
			levels[16].push("   ttt    ww   ");
			levels[16].push("          ww   ");
			levels[16].push("     tttt t    ");
			levels[16].push("     tttwww    ");
			levels[16].push("        www    ");
			levels[16].push("               ");
			levels[16].push("               ");
			levels[16].push("               ");
			levels[16].push("               ");
			levels[16].push([5, 8]);
			
			levels[17].push("               ");
			levels[17].push("               ");
			levels[17].push("               ");
			levels[17].push("               ");
			levels[17].push("      ww       ");
			levels[17].push("      ww ttt   ");
			levels[17].push("   twtttttxt   ");
			levels[17].push("   ww    ttt   ");
			levels[17].push("   ww          ");
			levels[17].push("    tww        ");
			levels[17].push("    www        ");
			levels[17].push("    tww        ");
			levels[17].push("               ");
			levels[17].push("               ");
			levels[17].push("               ");
			levels[17].push([4, 11]);
			
			levels[18].push("            ttt");
			levels[18].push("    twwt    txt");
			levels[18].push(" wwww  wwww ttt");
			levels[18].push(" wwww  wwww  w ");
			levels[18].push(" t        twwt ");
			levels[18].push(" wwwwwwwww     ");
			levels[18].push(" wwwwwwwww     ");
			levels[18].push("         t     ");
			levels[18].push("     wwwww     ");
			levels[18].push("     wwwww     ");
			levels[18].push("   wwt         ");
			levels[18].push("   ww   www    ");
			levels[18].push("   ww   www    ");
			levels[18].push("   wwtwwt twwt ");
			levels[18].push("               ");
			levels[18].push([13, 13]);
			
			levels[19].push("               ");
			levels[19].push("               ");
			levels[19].push("               ");
			levels[19].push("               ");
			levels[19].push("      www      ");
			levels[19].push(" www  www ttt  ");
			levels[19].push(" twtttt tttxt  ");
			levels[19].push(" ttt      ttt  ");
			levels[19].push("  t            ");
			levels[19].push("  t            ");
			levels[19].push("  t            ");
			levels[19].push("               ");
			levels[19].push("               ");
			levels[19].push("               ");
			levels[19].push("               ");
			levels[19].push([2, 10]);
			
			levels[20].push("               ");
			levels[20].push("               ");
			levels[20].push("               ");
			levels[20].push("        ttt    ");
			levels[20].push(" ttt tt tttt   ");
			levels[20].push(" ttt tt t  t   ");
			levels[20].push(" ttt ttwt ttt  ");
			levels[20].push("  w   w   txt  ");
			levels[20].push("  w   w   ttt  ");
			levels[20].push(" ttwtwtt       ");
			levels[20].push(" tt   tt       ");
			levels[20].push(" tt   tt       ");
			levels[20].push("               ");
			levels[20].push("               ");
			levels[20].push("               ");
			levels[20].push([2, 4]);
			
			levels[21].push("               ");
			levels[21].push("               ");
			levels[21].push("               ");
			levels[21].push("               ");
			levels[21].push("               ");
			levels[21].push("           ttt ");
			levels[21].push(" ttt  ttt  txt ");
			levels[21].push(" tttwwtttwwttt ");
			levels[21].push(" ttt  ttt  ttt ");
			levels[21].push("           ttt ");
			levels[21].push("               ");
			levels[21].push("               ");
			levels[21].push("               ");
			levels[21].push("               ");
			levels[21].push("               ");
			levels[21].push([1, 7]);
			
			levels[22].push("               ");
			levels[22].push("     twwwtww   ");
			levels[22].push("  wwwwwwwwww   ");
			levels[22].push("  wwwwwwwwww   ");
			levels[22].push("  twwtwwwtww   ");
			levels[22].push("        wwww   ");
			levels[22].push("        ttww   ");
			levels[22].push("     wwww      ");
			levels[22].push("     wwww      ");
			levels[22].push("     t         ");
			levels[22].push("     t         ");
			levels[22].push("    ttt        ");
			levels[22].push("    txt        ");
			levels[22].push("    ttt        ");
			levels[22].push("               ");
			levels[22].push([2, 4]);
			
			levels[23].push("ttttttttttttttt");
			levels[23].push("t        wwwwwt");
			levels[23].push("t wwwwww wtttwt");
			levels[23].push("t wtwwtw wtxtwt");
			levels[23].push("t wwwwwwwwtttwt");
			levels[23].push("t wwwwwwwwwwwwt");
			levels[23].push("t wtwwwwwwww  t");
			levels[23].push("t wwwwwwwwww  t");
			levels[23].push("t wwwtwwwttw  t");
			levels[23].push("t wtwwwwwwww  t");
			levels[23].push("t wwwwwwwwwt  t");
			levels[23].push("t wwwwwwwwww  t");
			levels[23].push("t wtwwwwtwww  t");
			levels[23].push("t             t");
			levels[23].push("ttttttttttttttt");
			levels[23].push([3, 12]);
			
			levels[24].push("               ");
			levels[24].push("    tww wwtwwt ");
			levels[24].push("    wwwtww  ww ");
			levels[24].push("    w      ttt ");
			levels[24].push("    ttwwt  txt ");
			levels[24].push("    ww  ww ttt ");
			levels[24].push("    ww  ww     ");
			levels[24].push("tw     wwt     ");
			levels[24].push("wt tww ww      ");
			levels[24].push("ttwtww ww      ");
			levels[24].push(" w w   ww      ");
			levels[24].push(" w twwtww      ");
			levels[24].push("ttt            ");
			levels[24].push("ttt            ");
			levels[24].push("ttt            ");
			levels[24].push([1, 14]);
			
			levels[25].push("               ");
			levels[25].push("    wwtww  ttt ");
			levels[25].push("twwtww wwt txt ");
			levels[25].push("w        wwttt ");
			levels[25].push("w wwtwwt wwww  ");
			levels[25].push("t ww   w       ");
			levels[25].push("wwww wwtwwww   ");
			levels[25].push("wwww wwtwwww   ");
			levels[25].push(" tww    wwttww ");
			levels[25].push("            ww ");
			levels[25].push("       wwwwwww ");
			levels[25].push(" ttt   wwwwwww ");
			levels[25].push(" ttttwwt   tww ");
			levels[25].push(" ttt           ");
			levels[25].push("               ");
			levels[25].push([2, 13]); /*Weak-tiles (10)*/
			
			levels[26].push("               ");
			levels[26].push("               ");
			levels[26].push("               ");
			levels[26].push("               ");
			levels[26].push("               ");
			levels[26].push("ttett          ");
			levels[26].push("ttttt  ttt ttt ");
			levels[26].push("tttttlrtttttxt ");
			levels[26].push("ttttt  ttt ttt ");
			levels[26].push("ttttt          ");
			levels[26].push("               ");
			levels[26].push("               ");
			levels[26].push("               ");
			levels[26].push("               ");
			levels[26].push("               ");
			levels[26].push([0, 9]);
			levels[26].push({sw25: [[5, 7, "on"], [6, 7, "on"]]});
			
			levels[27].push("               ");
			levels[27].push("               ");
			levels[27].push("               ");
			levels[27].push("               ");
			levels[27].push(" ttt ttt ett   ");
			levels[27].push(" txtlttttttt   ");
			levels[27].push(" ttt t   ttt   ");
			levels[27].push("     ttt   u   ");
			levels[27].push("     ttt   d   ");
			levels[27].push("ett  t    ttt  ");
			levels[27].push("tttlrttt  ett  ");
			levels[27].push("ttt  ttt       ");
			levels[27].push("               ");
			levels[27].push("               ");
			levels[27].push("               ");
			levels[27].push([1, 11]);
			levels[27].push({sw09: [[3, 10, "on"], [4, 10, "on"]], sw94: [[11, 7, "on"], [11, 8, "on"]], sw1010: [[4, 5, "on"]]});
			
			levels[28].push("               ");
			levels[28].push("               ");
			levels[28].push("         ttt   ");
			levels[28].push("         txt   ");
			levels[28].push("         ttt   ");
			levels[28].push("         ttt   ");
			levels[28].push("         ttt   ");
			levels[28].push("          u    ");
			levels[28].push("          d    ");
			levels[28].push("  ttt  ttht    ");
			levels[28].push("  thtlrtttt    ");
			levels[28].push("  ttt  tttt    ");
			levels[28].push("   t           ");
			levels[28].push("   t           ");
			levels[28].push("               ");
			levels[28].push([3, 13]);
			levels[28].push({sw310: [[5, 10, "on"], [6, 10, "on"]], sw99: [[10, 7, "on"], [10, 8, "on"]]});
			
			levels[29].push("               ");
			levels[29].push("               ");
			levels[29].push("          h    ");
			levels[29].push("  ttt     t    ");
			levels[29].push("  txt     t    ");
			levels[29].push("  ttt    ttt   ");
			levels[29].push("   t     ttt   ");
			levels[29].push("   u     ttt   ");
			levels[29].push("   d      u    ");
			levels[29].push("   ttt    d    ");
			levels[29].push("   ttthtttt    ");
			levels[29].push("   ttt   tt    ");
			levels[29].push("         tt    ");
			levels[29].push("               ");
			levels[29].push("               ");
			levels[29].push([4, 11]);
			levels[29].push({sw610: [[10, 8, "on"], [10, 9, "on"]], sw102: [[3, 7, "on"], [3, 8, "on"]]});
			
			levels[30].push("               ");
			levels[30].push("               ");
			levels[30].push("      ttt      ");
			levels[30].push("      tte      ");
			levels[30].push("      ttt      ");
			levels[30].push("       t       ");
			levels[30].push("  ttt  t ttt   ");
			levels[30].push("  ettlrtrtxt   ");
			levels[30].push("  ttt  u ttt   ");
			levels[30].push("       d       ");
			levels[30].push("      ttt      ");
			levels[30].push("      tht      ");
			levels[30].push("      ttt      ");
			levels[30].push("               ");
			levels[30].push("               ");
			levels[30].push([7, 7]);
			levels[30].push({sw83: [[7, 8, "on"], [7, 9, "on"]], sw711: [[5, 7, "on"], [6, 7, "on"]], sw27: [[8, 7, "on"]]});
			
			levels[31].push("ttt         ttt");
			levels[31].push("tet         txt");
			levels[31].push("ttttttt     ttt");
			levels[31].push("      tt     t ");
			levels[31].push("      tt  tttt ");
			levels[31].push(" ttt ttt  t    ");
			levels[31].push(" tttttt   t    ");
			levels[31].push(" tt      rtl   ");
			levels[31].push("  t      rtl   ");
			levels[31].push(" tt  ttttttl   ");
			levels[31].push(" tt  t         ");
			levels[31].push(" t   t  ttt    ");
			levels[31].push("ttttttttttt ttt");
			levels[31].push("ttt   ttt tttht");
			levels[31].push("ttt         ttt");
			levels[31].push([1, 14]);
			levels[31].push({sw11: [[9, 7, "on"], [9, 8, "on"]], sw1313: [[11, 7, "on"], [11, 8, "on"], [11, 9, "on"]]});
			
			levels[32].push("               ");
			levels[32].push("               ");
			levels[32].push("ttt  ttt       ");
			levels[32].push("tttlrtxt       ");
			levels[32].push("ttt  ttt       ");
			levels[32].push(" t             ");
			levels[32].push(" tttt  ttt  ttt");
			levels[32].push("  tttlrtttlrttt");
			levels[32].push("  tth  tet  tth");
			levels[32].push("   u           ");
			levels[32].push("  ttt  tth  ttt");
			levels[32].push("  tttlrtttlrttt");
			levels[32].push("  tet  ttt  tth");
			levels[32].push("               ");
			levels[32].push("               ");
			levels[32].push([1, 3]);
			levels[32].push({sw1412: [[3, 3, "on"], [4, 3, "on"]], sw910: [[5, 7, "on"], [6, 7, "on"]], sw88: [[10, 7, "on"], [11, 7, "on"]], sw48: [[3, 9, "on"]], sw312: [[5, 11, "on"], [6, 11, "on"]], sw148: [[10, 11, "on"], [11, 11, "on"]]});
			
			levels[33].push("               ");
			levels[33].push("          t    ");
			levels[33].push("          t    ");
			levels[33].push("  ttt tt tt    ");
			levels[33].push("  htt tt ttet  ");
			levels[33].push("  tt  htttttt  ");
			levels[33].push("   t   d  t    ");
			levels[33].push("   u  ttt t    ");
			levels[33].push("   d  txt t    ");
			levels[33].push("   t  ttt t    ");
			levels[33].push("  tt      t    ");
			levels[33].push("  ttlrtttttt   ");
			levels[33].push("  tttt    tt   ");
			levels[33].push("    tt    tt   ");
			levels[33].push("               ");
			levels[33].push([10, 1]);
			levels[33].push({sw24: [[7, 6, "on"]], sw65: [[4, 11, "on"], [5, 11, "on"]], sw114: [[3, 7, "on"], [3, 8, "on"]]}); /*Switches ON only (8)*/
			
			levels[34].push("       t       ");
			levels[34].push("      ttt      ");
			levels[34].push("     ttxtt     ");
			levels[34].push("    tvbtttt    ");
			levels[34].push("   ttt    tt   ");
			levels[34].push("  tt       tt  ");
			levels[34].push(" ett       ttt ");
			levels[34].push("tttt       tttt");
			levels[34].push("ttt    ttt  ttt");
			levels[34].push("tt   ttttt   tt");
			levels[34].push("ttt ttttet   tt");
			levels[34].push(" tvbtt t tt tt ");
			levels[34].push("  ttt  t  ttt  ");
			levels[34].push("      ttt      ");
			levels[34].push("    ttttttt    ");
			levels[34].push([4, 14]);
			levels[34].push({sw16: [[5, 3, "off"], [6, 3, "off"]], sw810: [[2, 11, "off"], [3, 11, "off"]]});
			
			levels[35].push(" ttt           ");
			levels[35].push("  ttttt        ");
			levels[35].push("   tvbtt       ");
			levels[35].push("    ttvbtt     ");
			levels[35].push("      t  t     ");
			levels[35].push("      t  t     ");
			levels[35].push("     tt  t     ");
			levels[35].push("     tt  t     ");
			levels[35].push("     t   t     ");
			levels[35].push("    tt   ttt   ");
			levels[35].push("  tttt  ttxtt  ");
			levels[35].push(" thttht ttttt  ");
			levels[35].push(" tthhtt ttttt  ");
			levels[35].push(" tttttt  ttt   ");
			levels[35].push("  tttt         ");
			levels[35].push([2, 14]);
			levels[35].push({sw211: [[4, 2, "off"]], sw312: [[5, 2, "off"]], sw412: [[6, 3, "off"]], sw511: [[7, 3, "off"]]});
			
			levels[36].push("               ");
			levels[36].push("       ttt     ");
			levels[36].push("       txtt    ");
			levels[36].push("       ttttbt  ");
			levels[36].push("  tttt     ttt ");
			levels[36].push("  tt t       t ");
			levels[36].push("  tt t  ttt  t ");
			levels[36].push("   t t  t t  t ");
			levels[36].push(" tttetbttetvtt ");
			levels[36].push(" tttetbttetttt ");
			levels[36].push(" t      t      ");
			levels[36].push(" t  ttt tv tt  ");
			levels[36].push(" httttt tv tt  ");
			levels[36].push(" tttt   htttt  ");
			levels[36].push("    t          ");
			levels[36].push([4, 14]);
			levels[36].push({sw112: [[11, 8, "off"]], sw48: [[6, 8, "off"]], sw49: [[6, 9, "off"]], sw98: [[9, 11, "off"]], sw99: [[9, 12, "off"]], sw813: [[11, 3, "off"]]});
			
			levels[37].push("               ");
			levels[37].push("               ");
			levels[37].push("      ttttttt  ");
			levels[37].push(" ttt  tet tbt  ");
			levels[37].push(" txt  t   tth  ");
			levels[37].push(" tttttt   t    ");
			levels[37].push(" nn      tt    ");
			levels[37].push("     ttt tt    ");
			levels[37].push("    tttv ttttt ");
			levels[37].push("    t  t    tt ");
			levels[37].push("    t  ttttttv ");
			levels[37].push("  thtet    tht ");
			levels[37].push("  ttttt        ");
			levels[37].push("  ttttt        ");
			levels[37].push("               ");
			levels[37].push([4, 12]);
			levels[37].push({sw311: [[7, 8, "off"]], sw511: [[13, 10, "off"]], sw1211: [[11, 3, "off"]], sw124: [[2, 6, "off"]], sw73: [[1, 6, "off"]]});
			
			levels[38].push("               ");
			levels[38].push("  tttt         ");
			levels[38].push("  t  t   tttt  ");
			levels[38].push("  t  tetttttt  ");
			levels[38].push("  t tttttt et  ");
			levels[38].push(" tt tt tt      ");
			levels[38].push(" tt tt         ");
			levels[38].push(" h    tt  tttt ");
			levels[38].push(" tttvbtt bt tt ");
			levels[38].push(" tttttttttt tt ");
			levels[38].push("   ttt  ttt ttt");
			levels[38].push("            ttt");
			levels[38].push("   tttt ttt  t ");
			levels[38].push("   txtt ttt  t ");
			levels[38].push("   tttttt tvbt ");
			levels[38].push([12, 2]);
			levels[38].push({sw114: [[4, 8, "off"], [5, 8, "off"]], sw63: [[11, 14, "off"], [12, 14, "off"]], sw17: [[9, 8, "off"]]}); /*Switches OFF only (5)*/
			
			levels[39].push("      ttt      ");
			levels[39].push("     ttxtt     ");
			levels[39].push("      ttt      ");
			levels[39].push("       u       ");
			levels[39].push("       d       ");
			levels[39].push("   t   t   t   ");
			levels[39].push("  ttt ttt tre  ");
			levels[39].push(" ttttrttttttte ");
			levels[39].push("  ett ttt ttt  ");
			levels[39].push("   t   t   t   ");
			levels[39].push("       t       ");
			levels[39].push("       t       ");
			levels[39].push("       t       ");
			levels[39].push("      ttt      ");
			levels[39].push("     ttttt     ");
			levels[39].push([7, 14]);
			levels[39].push({sw137: [[5, 7, "onoff"]], sw28: [[11, 6, "onoff"]], sw126: [[7, 3, "onoff"], [7, 4, "onoff"]]});
			
			levels[40].push("  ttt     ttt  ");
			levels[40].push(" tttt     txtt ");
			levels[40].push(" tlrtt   tttttt");
			levels[40].push("tt  ttt tttt  t");
			levels[40].push("tt    ttt     t");
			levels[40].push("te    trt    tt");
			levels[40].push(" ttt         tt");
			levels[40].push(" ttt        tt ");
			levels[40].push("  tt        t  ");
			levels[40].push("  ttt      tt  ");
			levels[40].push("   trt    tt   ");
			levels[40].push("    tttttte    ");
			levels[40].push("     ttett     ");
			levels[40].push("      ttt      ");
			levels[40].push("       t       ");
			levels[40].push([7, 14]);
			levels[40].push({sw712: [[4, 10, "onoff"]], sw1011: [[7, 5, "onoff"]], sw15: [[2, 2, "onoff"], [3, 2, "onoff"]]});
			
			levels[41].push("       t       ");
			levels[41].push("      ttt      ");
			levels[41].push("      txt      ");
			levels[41].push("      ttt      ");
			levels[41].push("     t rtt     ");
			levels[41].push("     t ttt     ");
			levels[41].push("    tt  ttt    ");
			levels[41].push("   ttttrtett   ");
			levels[41].push("    ttt ttt    ");
			levels[41].push("     te  t     ");
			levels[41].push("     tt  t     ");
			levels[41].push("      t t      ");
			levels[41].push("      ttt      ");
			levels[41].push("      ttt      ");
			levels[41].push("       t       ");
			levels[41].push([7, 14]);
			levels[41].push({sw69: [[7, 7, "onoff"]], sw97: [[7, 4, "onoff"]]});
			
			levels[42].push("               ");
			levels[42].push("               ");
			levels[42].push("               ");
			levels[42].push("ttttv          ");
			levels[42].push("txtttt         ");
			levels[42].push("ttt tt         ");
			levels[42].push("     httv ttt  ");
			levels[42].push("        tthtth ");
			levels[42].push("        ttt  u ");
			levels[42].push("             d ");
			levels[42].push(" hlrhlrhlrhlrh ");
			levels[42].push(" n             ");
			levels[42].push(" m             ");
			levels[42].push(" t             ");
			levels[42].push("               ");
			levels[42].push([1, 13]);
			levels[42].push({sw110: [[1, 12, "onoff"], [1, 11, "onoff"], [2, 10, "onoff"], [3, 10, "onoff"]], sw410: [[5, 10, "onoff"], [6, 10, "onoff"], [2, 10, "onoff"], [3, 10, "onoff"]], sw710: [[8, 10, "onoff"], [9, 10, "onoff"], [5, 10, "onoff"], [6, 10, "onoff"]], sw1010: [[11, 10, "onoff"], [12, 10, "onoff"], [8, 10, "onoff"], [9, 10, "onoff"]], sw1310: [[13, 9, "onoff"], [13, 8, "onoff"], [11, 10, "onoff"], [12, 10, "onoff"]], sw137: [[13, 9, "onoff"], [13, 8, "onoff"]], sw107: [[8, 6, "onoff"]], sw56: [[4, 3, "onoff"]]});
			
			levels[43].push("               ");
			levels[43].push("               ");
			levels[43].push("  tt  ttv      ");
			levels[43].push("  tt  ttt      ");
			levels[43].push("  tttth ttt    ");
			levels[43].push("  u      rth   ");
			levels[43].push(" ttt   tl  u   ");
			levels[43].push(" txt   tl  d   ");
			levels[43].push(" ttt   httth   ");
			levels[43].push("  t  tt   t    ");
			levels[43].push("  t  tt   t    ");
			levels[43].push("  ttttttttt    ");
			levels[43].push("      tt       ");
			levels[43].push("      tt       ");
			levels[43].push("               ");
			levels[43].push([2, 8]);
			levels[43].push({sw78: [[8, 7, "onoff"], [8, 6, "onoff"], [8, 2, "onoff"]], sw118: [[11, 7, "onoff"], [11, 6, "onoff"]], sw115: [[9, 5, "onoff"], [8, 2, "onoff"]], sw64: [[2, 5, "onoff"]]});
			
			levels[44].push("               ");
			levels[44].push("        ttt    ");
			levels[44].push("        txt    ");
			levels[44].push("   hlrh ttt    ");
			levels[44].push("   u  n  tt    ");
			levels[44].push("   d  m  t     ");
			levels[44].push("   hvbh  ttt   ");
			levels[44].push("   t  t  ttt   ");
			levels[44].push("   t  t  t     ");
			levels[44].push(" ttt  tlrt     ");
			levels[44].push(" ttt           ");
			levels[44].push(" ttt           ");
			levels[44].push("               ");
			levels[44].push("               ");
			levels[44].push("               ");
			levels[44].push([2, 11]);
			levels[44].push({sw36: [[3, 5, "onoff"], [3, 4, "onoff"], [4, 6, "onoff"], [5, 6, "onoff"]], sw33: [[3, 5, "onoff"], [3, 4, "onoff"], [4, 3, "onoff"], [5, 3, "onoff"]], sw63: [[6, 4, "onoff"], [6, 5, "onoff"]], sw66: [[7, 9, "onoff"], [8, 9, "onoff"]]});
			
			levels[45].push("               ");
			levels[45].push("   tv    hhhhh ");
			levels[45].push("   ttt  rttttt ");
			levels[45].push("    tt  bttttt ");
			levels[45].push("  ttrtttt    t ");
			levels[45].push("  ttt        t ");
			levels[45].push("    t        t ");
			levels[45].push("   ttt    tttt ");
			levels[45].push("   txt  ttl    ");
			levels[45].push("   ttt  ttttttt");
			levels[45].push("   uuu  tte   t");
			levels[45].push("   tbt       tt");
			levels[45].push("   tbtthttttttt");
			levels[45].push("   tbt    tt   ");
			levels[45].push("          tt   ");
			levels[45].push([4, 12]);
			levels[45].push({sw712: [[4, 11, "off"], [4, 12, "off"], [4, 13, "off"], [3, 10, "on"], [4, 10, "on"], [5, 10, "on"]], sw1010: [[10, 8, "onoff"]], sw131: [[4, 1, "onoff"]], sw121: [[8, 2, "onoff"]], sw111: [[4, 4, "onoff"]], sw101: [[4, 1, "off"]], sw91: [[8, 3, "onoff"]]});
			
			levels[46].push("tth  htth      ");
			levels[46].push("tttttttttttttth");
			levels[46].push("tt           tt");
			levels[46].push("tt tttttttt  tt");
			levels[46].push("tt ttluthtth th");
			levels[46].push("tt ttlrtlurt t ");
			levels[46].push("tt ttrtttlrt t ");
			levels[46].push("tt ttrtxtttt t ");
			levels[46].push("tttttlttttt  t ");
			levels[46].push("  u  rttttt  t ");
			levels[46].push(" ttt ddddddttt ");
			levels[46].push(" tttttttttttt  ");
			levels[46].push(" t             ");
			levels[46].push(" tttttttttttttt");
			levels[46].push("       htth ttt");
			levels[46].push([13, 13]);
			levels[46].push({sw714: [[2, 9, "onoff"]], sw1014: [[6, 10, "onoff"]], sw144: [[8, 10, "onoff"]], sw141: [[8, 10, "onoff"]], sw50: [], sw80: [[5, 9, "onoff"]], sw20: [[6, 10, "onoff"]], sw84: [[5, 8, "onoff"], [5, 7, "onoff"], [5, 6, "onoff"], [5, 5, "onoff"], [5, 4, "onoff"], [6, 4, "onoff"]], sw114: [[9, 5, "onoff"], [10, 5, "onoff"], [9, 6, "onoff"], [10, 6, "onoff"], [9, 10, "onoff"], [10, 10, "onoff"]]});
			
			levels[47].push("  tttttttttt   ");
			levels[47].push("  ttttttttttt  ");
			levels[47].push("  u d     txt  ");
			levels[47].push("  etttet  ttt  ");
			levels[47].push("  tetttt       ");
			levels[47].push("       u       ");
			levels[47].push("  trtttt       ");
			levels[47].push("  t   tt       ");
			levels[47].push("  t   httrh    ");
			levels[47].push(" ttl    ttt    ");
			levels[47].push(" ett    ttt    ");
			levels[47].push(" ttt           ");
			levels[47].push("               ");
			levels[47].push("               ");
			levels[47].push("               ");
			levels[47].push([2, 11]);
			levels[47].push({sw110: [[3, 9, "onoff"], [3, 6, "onoff"]], sw68: [[7, 5, "onoff"]], sw108: [[9, 8, "onoff"]], sw63: [[4, 2, "onoff"]], sw34: [[2, 2, "onoff"]], sw23: [[2, 2, "onoff"]]});
			
			levels[48].push(" tttttt        ");
			levels[48].push(" t   ttttt     ");
			levels[48].push(" t      tt     ");
			levels[48].push(" thttt  ttt    ");
			levels[48].push(" bt  t    t    ");
			levels[48].push(" bt  t    t    ");
			levels[48].push(" th  t  ttt    ");
			levels[48].push(" bt tt  tl ttt ");
			levels[48].push(" bt btt tttttt ");
			levels[48].push(" hh ttth   ttt ");
			levels[48].push("       e    t  ");
			levels[48].push(" tt    t   ttt ");
			levels[48].push(" ttttttt   txt ");
			levels[48].push(" ttt       ttt ");
			levels[48].push("               ");
			levels[48].push([2, 13]);
			levels[48].push({sw710: [[4, 8, "onoff"]], sw79: [[9, 7, "onoff"]], sw23: [[1, 4, "onoff"], [1, 5, "onoff"]], sw26: [[1, 7, "onoff"], [1, 8, "onoff"]], sw19: [[1, 4, "onoff"], [1, 5, "onoff"]], sw29: [[1, 7, "onoff"], [1, 8, "onoff"]]});
			
			levels[49].push("ttttt          ");
			levels[49].push("txttt          ");
			levels[49].push("ttttt          ");
			levels[49].push("ttttt          ");
			levels[49].push("tttttlrh       ");
			levels[49].push("    u  n       ");
			levels[49].push("    d  m       ");
			levels[49].push("    hvbtlrh    ");
			levels[49].push("       u  u    ");
			levels[49].push("       d  d    ");
			levels[49].push("       hlrhttbh");
			levels[49].push("          ttbet");
			levels[49].push("          tbett");
			levels[49].push("          tettt");
			levels[49].push("          htttt");
			levels[49].push([14, 14]);
			levels[49].push({sw1113: [[11, 12, "onoff"]], sw1212: [[10, 11, "onoff"]], sw1311: [[9, 10, "onoff"]], sw1014: [[10, 9, "onoff"], [10, 8, "onoff"]], sw1410: [[8, 10, "onoff"], [9, 10, "onoff"]], sw1010: [[7, 5, "onoff"], [7, 6, "onoff"], [5, 7, "onoff"], [6, 7, "onoff"]], sw710: [[8, 7, "onoff"], [9, 7, "onoff"]], sw107: [[7, 8, "onoff"], [7, 9, "onoff"]], sw74: [[5, 4, "onoff"], [6, 4, "onoff"]], sw47: [[4, 5, "onoff"], [4, 6, "onoff"]]});
			
			levels[50].push("      ttt      ");
			levels[50].push(" ttttrtxtlttt  ");
			levels[50].push(" tt   ttt  ttl ");
			levels[50].push(" ttl   u    tt ");
			levels[50].push("   t   t    tt ");
			levels[50].push("   tt  h  tth  ");
			levels[50].push("   tt  t  ttttt");
			levels[50].push(" ttth  t     tt");
			levels[50].push(" tt    t    htt");
			levels[50].push(" tt    u    tt ");
			levels[50].push(" htt   d    tt ");
			levels[50].push(" ttttlrhlrttttt");
			levels[50].push(" tt    t     tt");
			levels[50].push(" tt    t     tt");
			levels[50].push("       t       ");
			levels[50].push([7, 14]);
			levels[50].push({sw75: [[7, 3, "on"], [5, 1, "off"], [9, 1, "off"]], sw125: [[13, 2, "onoff"]], sw47: [[3, 3, "onoff"]], sw128: [[7, 3, "off"], [5, 1, "off"], [9, 1, "on"]], sw110: [[5, 1, "on"], [9, 1, "off"], [7, 3, "off"]], sw711: [[5, 11, "on"], [6, 11, "on"], [7, 10, "on"], [7, 9, "on"], [8, 11, "on"], [9, 11, "on"]]}); /*Switches ON+OFF (12)*/
			
			levels[51].push("               ");
			levels[51].push("          ttt  ");
			levels[51].push("          txt  ");
			levels[51].push("          ttt  ");
			levels[51].push("           t   ");
			levels[51].push("       ttttt   ");
			levels[51].push("     ttt   tt  ");
			levels[51].push("    tt      tt ");
			levels[51].push("   tt        t ");
			levels[51].push("  tt        tt ");
			levels[51].push("  t        tt  ");
			levels[51].push("          tt   ");
			levels[51].push("  ttts  ttt    ");
			levels[51].push("               ");
			levels[51].push("               ");
			levels[51].push([2, 12]);
			levels[51].push({});
			levels[51].push({sw512: [2, 9, 8, 12]});
			
			levels[52].push("               ");
			levels[52].push(" tttt      ttt ");
			levels[52].push(" tttts   ttttt ");
			levels[52].push(" tt     tt ttt ");
			levels[52].push("       tt      ");
			levels[52].push("     ttt       ");
			levels[52].push("   ttt   tts   ");
			levels[52].push("   ttt   ttt   ");
			levels[52].push("   ttttttttt   ");
			levels[52].push("          t    ");
			levels[52].push("   ttttt tt    ");
			levels[52].push(" ttt   ttt ttt ");
			levels[52].push(" ttt      ttxt ");
			levels[52].push(" ttttttttttttt ");
			levels[52].push("               ");
			levels[52].push([1, 1]);
			levels[52].push({});
			levels[52].push({sw52: [12, 2, 4, 7], sw116: [10, 8, 1, 11]});
			
			levels[53].push("               ");
			levels[53].push("               ");
			levels[53].push("  tttt  ttttt  ");
			levels[53].push("  t  t  t   t  ");
			levels[53].push("  t  t  t   t  ");
			levels[53].push("  sttttttttts  ");
			levels[53].push("               ");
			levels[53].push("               ");
			levels[53].push("  tttttttttt   ");
			levels[53].push("  t  t  t  t   ");
			levels[53].push("  t  t  t  t   ");
			levels[53].push("  tttt  tttttt ");
			levels[53].push("           txt ");
			levels[53].push("           ttt ");
			levels[53].push("            t  ");
			levels[53].push([2, 2]);
			levels[53].push({});
			levels[53].push({sw25: [3, 2, 5, 2], sw125: [2, 9, 2, 11]});
			
			levels[54].push("          t    ");
			levels[54].push("          tt   ");
			levels[54].push("     ttt   t   ");
			levels[54].push(" tttttxttttt   ");
			levels[54].push(" t   ttt       ");
			levels[54].push(" tt            ");
			levels[54].push("  t    sttt    ");
			levels[54].push("       t  tt   ");
			levels[54].push("   ttt t   t   ");
			levels[54].push(" ttt t ttt ttt ");
			levels[54].push(" t   t   t   t ");
			levels[54].push(" tts ttt tt  t ");
			levels[54].push(" ttt   s  tttt ");
			levels[54].push(" stttt t       ");
			levels[54].push("     ttt       ");
			levels[54].push([1, 13]);
			levels[54].push({});
			levels[54].push({sw311: [1, 11, 3, 13], sw712: [12, 12, 13, 11], sw76: [2, 6, 10, 0]});
			
			levels[55].push("               ");
			levels[55].push("               ");
			levels[55].push("               ");
			levels[55].push("               ");
			levels[55].push("       ttt     ");
			levels[55].push("  ttt  ttt     ");
			levels[55].push("  tttttt ttt   ");
			levels[55].push("  ttt    ttt   ");
			levels[55].push("          tttt ");
			levels[55].push("   tttt     tt ");
			levels[55].push("tttt  t   tttt ");
			levels[55].push("t    ttt ttt   ");
			levels[55].push("t ttttxt tst   ");
			levels[55].push("ttt  ttt ttt   ");
			levels[55].push("               ");
			levels[55].push([2, 6]);
			levels[55].push({});
			levels[55].push({sw1012: [0, 11, 1, 10]});
			
			levels[56].push("               ");
			levels[56].push(" ttt t  t  s t ");
			levels[56].push(" txttt  t  t   ");
			levels[56].push(" ttt t  tttt t ");
			levels[56].push("  t   s t  t t ");
			levels[56].push("      t t  t t ");
			levels[56].push("     ttt       ");
			levels[56].push("    tt ttt     ");
			levels[56].push("   tt s  t     ");
			levels[56].push("  tt  t  t     ");
			levels[56].push("      t  t ttt ");
			levels[56].push("     ttt t t t ");
			levels[56].push("  tttttt t   t ");
			levels[56].push("     tt  ttttt ");
			levels[56].push("               ");
			levels[56].push([2, 12]);
			levels[56].push({});
			levels[56].push({sw68: [2, 9, 11, 11], sw64: [8, 1, 8, 5], sw111: [1, 1, 5, 1]});
			
			levels[57].push("               ");
			levels[57].push("               ");
			levels[57].push("               ");
			levels[57].push("               ");
			levels[57].push(" ttt           ");
			levels[57].push(" txt   t       ");
			levels[57].push(" ttt  tt t     ");
			levels[57].push("  t  tts tt    ");
			levels[57].push("         st    ");
			levels[57].push("   ttst  tt    ");
			levels[57].push("    t    tt    ");
			levels[57].push("  s t tt       ");
			levels[57].push("  t    stt     ");
			levels[57].push("  t   tt       ");
			levels[57].push("  t            ");
			levels[57].push([2, 14]);
			levels[57].push({});
			levels[57].push({sw211: [4, 9, 6, 9], sw59: [6, 11, 6, 13], sw712: [9, 6, 10, 7], sw98: [6, 6, 7, 5], sw77: [1, 4, 3, 4]});
			
			levels[58].push("        tt     ");
			levels[58].push("    ttt tt     ");
			levels[58].push("  tttttttt     ");
			levels[58].push("  t  tt     stt");
			levels[58].push("  t          tt");
			levels[58].push("  s         ttt");
			levels[58].push(" ttt      ttt  ");
			levels[58].push(" txt      ttttt");
			levels[58].push(" ttt ttt    ttt");
			levels[58].push("     t      t  ");
			levels[58].push("    ts      t  ");
			levels[58].push("  ttt   ttt t  ");
			levels[58].push("       ttttttt ");
			levels[58].push("        ttt    ");
			levels[58].push("               ");
			levels[58].push([5, 1]);
			levels[58].push({});
			levels[58].push({sw25: [2, 11, 7, 8], sw510: [7, 12, 7, 12], sw123: [1, 8, 3, 8]});
			
			levels[59].push("               ");
			levels[59].push("       tttttttt");
			levels[59].push(" ttt   ttt  stt");
			levels[59].push(" txtt  tttt    ");
			levels[59].push(" ttt     tt    ");
			levels[59].push("      ttttt    ");
			levels[59].push("      tt       ");
			levels[59].push("     tttt      ");
			levels[59].push("   t tt    ttt ");
			levels[59].push("   t tt    ttt ");
			levels[59].push("  tst        t ");
			levels[59].push("  t t  s     t ");
			levels[59].push("  t t  ttttttt ");
			levels[59].push("  t t  ttttttt ");
			levels[59].push("               ");
			levels[59].push([13, 13]);
			levels[59].push({});
			levels[59].push({sw711: [2, 13, 4, 13], sw310: [8, 7, 8, 7], sw122: [2, 2, 2, 4]});
			
			levels[60].push("               ");
			levels[60].push("tttt          t");
			levels[60].push("t             t");
			levels[60].push("t    tttttt   s");
			levels[60].push("s tt t ttxt ttt");
			levels[60].push("t  t t ttxt t t");
			levels[60].push("tttt tttttt ttt");
			levels[60].push("               ");
			levels[60].push(" t         t t ");
			levels[60].push(" t         t t ");
			levels[60].push(" t t t ttt t t ");
			levels[60].push(" t t t t   tt  ");
			levels[60].push(" t t t t   t t ");
			levels[60].push(" s tts tts t t ");
			levels[60].push("               ");
			levels[60].push([3, 1]);
			levels[60].push({});
			levels[60].push({sw04: [1, 8, 1, 9], sw113: [3, 10, 5, 10], sw513: [12, 4, 14, 6], sw143: [7, 10, 9, 10], sw913: [5, 3, 10, 6]}); /*Separators (10)*/
			
			levels[61].push("           ttt ");
			levels[61].push("           ttt ");
			levels[61].push("   terts   ttt ");
			levels[61].push("  tt   tt  t   ");
			levels[61].push(" tt     tt t   ");
			levels[61].push("           t   ");
			levels[61].push("           t   ");
			levels[61].push(" twtw      t   ");
			levels[61].push(" wtwt     wtt  ");
			levels[61].push(" s  ttt  tttt  ");
			levels[61].push("   tttt  t tt  ");
			levels[61].push("  ttt   ttt    ");
			levels[61].push(" ttt    txt    ");
			levels[61].push(" ttt    ttt    ");
			levels[61].push("               ");
			levels[61].push([2, 13]);
			levels[61].push({sw42: [[5, 2, "onoff"]]});
			levels[61].push({sw19: [1, 4, 9, 4], sw72: [13, 0, 13, 0]});
			
			levels[62].push("               ");
			levels[62].push("    tthtt  htt ");
			levels[62].push("      u    stt ");
			levels[62].push("    tttttt tt  ");
			levels[62].push("    ttt tt     ");
			levels[62].push("        tt     ");
			levels[62].push(" ttt  tet      ");
			levels[62].push(" t t  tt       ");
			levels[62].push("  tt  tttt wwh ");
			levels[62].push("  u     tt www ");
			levels[62].push(" ttt    ttvwwww");
			levels[62].push(" txtrt     wwtw");
			levels[62].push(" ttt t ttwwwww ");
			levels[62].push("     ttt wwwww ");
			levels[62].push("         s     ");
			levels[62].push([12, 1]);
			levels[62].push({sw61: [[4, 11, "onoff"]], sw111: [[6, 2, "onoff"]], sw76: [[10, 10, "onoff"]], sw138: [[2, 9, "onoff"]]});
			levels[62].push({sw112: [4, 1, 8, 1], sw914: [1, 7, 8, 12]});
			
			levels[63].push(" ttt           ");
			levels[63].push(" txt           ");
			levels[63].push(" ttt           ");
			levels[63].push("  t   ttth     ");
			levels[63].push("  t   t tt     ");
			levels[63].push(" tt     ttw    ");
			levels[63].push(" t      ttw    ");
			levels[63].push(" tt      t     ");
			levels[63].push("  t ttt  s     ");
			levels[63].push("  tlttt  u     ");
			levels[63].push(" wtt  t  d     ");
			levels[63].push(" ttt  ttth     ");
			levels[63].push(" tttwwt        ");
			levels[63].push("               ");
			levels[63].push("               ");
			levels[63].push([2, 12]);
			levels[63].push({sw93: [[3, 9, "onoff"]], sw911: [[9, 9, "on"], [9, 10, "on"]]});
			levels[63].push({sw98: [6, 4, 9, 7]});
			
			levels[64].push("               ");
			levels[64].push("               ");
			levels[64].push("  t       t    ");
			levels[64].push("  t  s   ttt   ");
			levels[64].push("  tttt  ttxtt  ");
			levels[64].push("tttttt   ttt   ");
			levels[64].push("ttt       t    ");
			levels[64].push("               ");
			levels[64].push("  tele    stt  ");
			levels[64].push("     u     ww  ");
			levels[64].push("  tlre  tt tt  ");
			levels[64].push("  t     tt ww  ");
			levels[64].push("  wtttttttttt  ");
			levels[64].push("         tt    ");
			levels[64].push("         tt    ");
			levels[64].push([2, 2]);
			levels[64].push({sw38: [[4, 8, "onoff"]], sw58: [[5, 9, "onoff"]], sw510: [[3, 10, "onoff"], [4, 10, "onoff"]]});
			levels[64].push({sw53: [2, 8, 2, 10], sw108: [10, 2, 10, 6]});
			
			levels[65].push("               ");
			levels[65].push("               ");
			levels[65].push("  ttt  htt     ");
			levels[65].push("  ttelrttt     ");
			levels[65].push("  htt  tet     ");
			levels[65].push("    u    u     ");
			levels[65].push("    d    d     ");
			levels[65].push("    stt  ttt   ");
			levels[65].push("    ttt  ttt   ");
			levels[65].push("    tth  tth   ");
			levels[65].push("           u   ");
			levels[65].push("           dd  ");
			levels[65].push("      tts  ttt ");
			levels[65].push("      ttw  txt ");
			levels[65].push("      ttt  ttt ");
			levels[65].push([7, 14]);
			levels[65].push({sw43: [[5, 3, "onoff"]], sw84: [[6, 3, "onoff"]], sw24: [[9, 5, "onoff"], [9, 6, "onoff"]], sw72: [[4, 5, "onoff"], [4, 6, "onoff"]], sw69: [[12, 11, "onoff"]], sw119: [[11, 10, "onoff"], [11, 11, "onoff"]]});
			levels[65].push({sw812: [2, 2, 9, 2], sw47: [5, 8, 10, 8]});
			
			levels[66].push("wwtww wwtww wwt");
			levels[66].push("ww wwtww wwtww ");
			levels[66].push("ttt h     t    ");
			levels[66].push(" ww t     t    ");
			levels[66].push(" wwttt tttt    ");
			levels[66].push("    tttttww    ");
			levels[66].push("         ww tww");
			levels[66].push("ttt wwtttt  tww");
			levels[66].push("wwttww ud   t t");
			levels[66].push("ww    thttwwt t");
			levels[66].push(" tttttttttwwt t");
			levels[66].push("  t   t      du");
			levels[66].push("  t   wwt   ttt");
			levels[66].push("  ttetwwtww txt");
			levels[66].push("        tww ttt");
			levels[66].push([14, 0]);
			levels[66].push({sw42: [[13, 11, "onoff"]], sw79: [[7, 8, "onoff"], [8, 8, "onoff"]], sw413: [[14, 11, "onoff"]]});
			
			levels[67].push("               ");
			levels[67].push("               ");
			levels[67].push("  ttttttttth   ");
			levels[67].push("  tttttttttt   ");
			levels[67].push(" ttt       ttt ");
			levels[67].push(" ttt       ttt ");
			levels[67].push("      tts  s   ");
			levels[67].push("      txtl     ");
			levels[67].push("      ttt      ");
			levels[67].push(" ttt           ");
			levels[67].push("stttt          ");
			levels[67].push("   ttts        ");
			levels[67].push("  ttttt        ");
			levels[67].push("   t           ");
			levels[67].push("               ");
			levels[67].push([6, 6]);
			levels[67].push({sw112: [[9, 7, "onoff"]]});
			levels[67].push({sw116: [6, 8, 8, 8], sw86: [2, 12, 3, 13], sw010: [3, 4, 3, 4], sw611: [6, 8, 8, 8]});
			
			levels[68].push("       w       ");
			levels[68].push("       t       ");
			levels[68].push("      ttt      ");
			levels[68].push("     ttstt     ");
			levels[68].push("       n       ");
			levels[68].push("      ttt      ");
			levels[68].push("     ttttt     ");
			levels[68].push("   httttwttt   ");
			levels[68].push("   e   u   e   ");
			levels[68].push("     wwtww     ");
			levels[68].push("   tlwwwwwtt   ");
			levels[68].push("  ttvwwwwwwww  ");
			levels[68].push("etttlwwwwwwtwws");
			levels[68].push("t     txt      ");
			levels[68].push("      ttt      ");
			levels[68].push([7, 1]);
			levels[68].push({sw37: [[7, 8, "onoff"], [7, 4, "onoff"]], sw38: [[4, 10, "on"]], sw118: [[4, 11, "off"]], sw012: [[4, 12, "onoff"]]});
			levels[68].push({sw73: [5, 3, 9, 3], sw1412: [0, 13, 1, 12]});
			
			levels[69].push("      ttt      ");
			levels[69].push("      ttt      ");
			levels[69].push("  tttltst ett  ");
			levels[69].push("  ttt     ttt  ");
			levels[69].push("  the wttrttt  ");
			levels[69].push("   u  wth  d   ");
			levels[69].push("  www wtt ttt  ");
			levels[69].push("  www  u  tth  ");
			levels[69].push("  hwwrttt ttt  ");
			levels[69].push("      tht      ");
			levels[69].push("      stt      ");
			levels[69].push("       d       ");
			levels[69].push("      ttt      ");
			levels[69].push("      txt      ");
			levels[69].push("      ttt      ");
			levels[69].push([7, 0]);
			levels[69].push({sw102: [[11, 5, "onoff"]], sw44: [[5, 2, "onoff"]], sw85: [[7, 7, "onoff"]], sw127: [[9, 4, "onoff"]], sw28: [[5, 8, "onoff"]], sw79: [[7, 11, "onoff"]], sw34: [[3, 5, "onoff"]]});
			levels[69].push({sw72: [8, 2, 2, 2], sw610: [10, 6, 12, 4]});
			
			levels[70].push("               ");
			levels[70].push("               ");
			levels[70].push("               ");
			levels[70].push("     s         ");
			levels[70].push(" t  tt   stt   ");
			levels[70].push(" t  tl   ttt   ");
			levels[70].push(" hlrtte tttt   ");
			levels[70].push(" tttttt  tt    ");
			levels[70].push("               ");
			levels[70].push("     t  slrt   ");
			levels[70].push(" ttt s     tt  ");
			levels[70].push(" txt ttt  tttt ");
			levels[70].push(" ttt t  tttttt ");
			levels[70].push("  t    htt  tt ");
			levels[70].push("               ");
			levels[70].push([12, 12]);
			levels[70].push({sw16: [[5, 5, "onoff"]], sw66: [[2, 6, "onoff"], [3, 6, "onoff"]], sw713: [[9, 9, "onoff"], [10, 9, "onoff"]]});
			levels[70].push({sw53: [8, 6, 8, 6], sw94: [1, 10, 3, 12], sw89: [5, 9, 5, 11], sw510: [4, 6, 5, 7]});
			
			levels[71].push("               ");
			levels[71].push(" wwrttshttttt  ");
			levels[71].push(" ww      thtl  ");
			levels[71].push(" ttt h   ttt   ");
			levels[71].push("  wwtw         ");
			levels[71].push("  wwww         ");
			levels[71].push("    t          ");
			levels[71].push("    ttttttt    ");
			levels[71].push("    w     tl   ");
			levels[71].push(" ww w      t   ");
			levels[71].push(" wtwt     ttt  ");
			levels[71].push(" ttww     txt  ");
			levels[71].push("  www     ttt  ");
			levels[71].push("               ");
			levels[71].push("               ");
			levels[71].push([1, 11]);
			levels[71].push({sw71: [[12, 2, "onoff"]], sw102: [[11, 8, "onoff"]], sw53: [[3, 1, "onoff"]]});
			levels[71].push({sw61: [10, 1, 10, 3]});
			
			levels[72].push("               ");
			levels[72].push("  tt   t   tt  ");
			levels[72].push("   tt  t  tt   ");
			levels[72].push("    ts t tt    ");
			levels[72].push(" et  rtstl  tt ");
			levels[72].push("  tt thttt tt  ");
			levels[72].push("   tttttttel   ");
			levels[72].push("    ttnmntt    ");
			levels[72].push("  trtveeebtrt  ");
			levels[72].push(" et  bexev  te ");
			levels[72].push("    t ttt t    ");
			levels[72].push("   tt trt tt   ");
			levels[72].push("  tt tt tt tt  ");
			levels[72].push("     t   t     ");
			levels[72].push("               ");
			levels[72].push([7, 1]);
			levels[72].push({sw14: [[9, 4, "on"]], sw19: [[11, 8, "onoff"]], sw139: [[7, 11, "onoff"], [5, 4, "onoff"]], sw106: [[11, 6, "onoff"]], sw65: [[3, 8, "onoff"]],
				sw69: [[5, 9, "off"], [5, 8, "off"], [6, 7, "off"], [7, 7, "off"], [8, 7, "off"], [9, 8, "off"], [9, 9, "off"]],
				sw68: [[5, 9, "off"], [5, 8, "off"], [6, 7, "off"], [7, 7, "off"], [8, 7, "off"], [9, 8, "off"], [9, 9, "off"]],
				sw78: [[5, 9, "off"], [5, 8, "off"], [6, 7, "off"], [7, 7, "off"], [8, 7, "off"], [9, 8, "off"], [9, 9, "off"]],
				sw88: [[5, 9, "off"], [5, 8, "off"], [6, 7, "off"], [7, 7, "off"], [8, 7, "off"], [9, 8, "off"], [9, 9, "off"]],
				sw89: [[5, 9, "off"], [5, 8, "off"], [6, 7, "off"], [7, 7, "off"], [8, 7, "off"], [9, 8, "off"], [9, 9, "off"]]});
			levels[72].push({sw53: [5, 13, 9, 13], sw74: [6, 4, 12, 1]});
			
			levels[73].push("  ww     ww    ");
			levels[73].push("  ww     ww    ");
			levels[73].push("  ttttttttt    ");
			levels[73].push("  u  tt        ");
			levels[73].push(" ttt wwlww     ");
			levels[73].push(" txt    et     ");
			levels[73].push(" ttt ww tt     ");
			levels[73].push("     ww ww  ww ");
			levels[73].push("  twwtt tt  ww ");
			levels[73].push("  wtww  ttltht ");
			levels[73].push("  ww           ");
			levels[73].push("   t twws ets  ");
			levels[73].push("   tww     tt  ");
			levels[73].push("   tww     t   ");
			levels[73].push("               ");
			levels[73].push([3, 13]);
			levels[73].push({sw85: [[10, 9, "onoff"]], sw1011: [[2, 3, "onoff"]], sw129: [[7, 4, "onoff"]]});
			levels[73].push({sw1211: [8, 9, 11, 9], sw811: [11, 13, 12, 12]});
			
			levels[74].push("               ");
			levels[74].push("    htvh       ");
			levels[74].push("    t  n       ");
			levels[74].push("   et  t       ");
			levels[74].push("   tttthltt    ");
			levels[74].push(" ttttt    t    ");
			levels[74].push(" t        tl   ");
			levels[74].push(" t  s    ttt   ");
			levels[74].push(" te wwww ttttt ");
			levels[74].push("    twww ttt t ");
			levels[74].push("   wwwwt     t ");
			levels[74].push("  www    ttttt ");
			levels[74].push(" wwt     txtl  ");
			levels[74].push(" wtt     ttt   ");
			levels[74].push("               ");
			levels[74].push([2, 13]);
			levels[74].push({sw41: [[7, 2, "off"]], sw71: [[8, 4, "onoff"]], sw74: [[6, 1, "off"]], sw33: [[11, 6, "onoff"]], sw28: [[12, 12, "onoff"]]});
			levels[74].push({sw47: [4, 4, 6, 4]});
			
			levels[75].push("      htt      ");
			levels[75].push("     thlts     ");
			levels[75].push("    tt   tt    ");
			levels[75].push("   tt  t  et   ");
			levels[75].push("  tele u ertt  ");
			levels[75].push(" st t  t  t ts ");
			levels[75].push("tt    ttt    tt");
			levels[75].push("tl tlttxttlt rt");
			levels[75].push("ht    ttt    hh");
			levels[75].push(" te t  t  t et ");
			levels[75].push("  ttltlu t tt  ");
			levels[75].push("   tt  t  tt   ");
			levels[75].push("    tt   tt    ");
			levels[75].push("     tt tt     ");
			levels[75].push("      sttt      ");
			levels[75].push([9, 14]);
			levels[75].push({sw60: [[7, 1, "onoff"]], sw61: [[6, 10, "onoff"]], sw103: [[10, 4, "onoff"]], sw34: [[4, 4, "onoff"]], sw54: [[10, 7, "onoff"]], sw94: [[7, 10, "onoff"]], sw08: [[1, 7, "onoff"]], sw138: [[4, 10, "onoff"]], sw148: [[13, 7, "onoff"]], sw29: [[10, 4, "onoff"]], sw129: [[4, 7, "onoff"]]});
			levels[75].push({sw91: [5, 12, 9, 12], sw15: [4, 12, 10, 12], sw135: [5, 12, 9, 12], sw614: [5, 13, 9, 13]});
			
			levels[76].push(" tttt          ");
			levels[76].push(" rtht       tt ");
			levels[76].push("  ttt tttl  tt ");
			levels[76].push("    tttttt  t  ");
			levels[76].push(" t  ttt  t  t  ");
			levels[76].push("ttt      t  t  ");
			levels[76].push(" t       t  t  ");
			levels[76].push("    tttttt tt  ");
			levels[76].push(" tt ttttte tt  ");
			levels[76].push(" tt t    t     ");
			levels[76].push(" thttl   t ttt ");
			levels[76].push("    tttt tttxt ");
			levels[76].push("     ttl   ttt ");
			levels[76].push("   ttt         ");
			levels[76].push("   ett         ");
			levels[76].push([7, 11]);
			levels[76].push({sw31: [[9, 2, "onoff"]], sw98: [[1, 1, "onoff"]], sw210: [[5, 10, "onoff"]], sw314: [[7, 12, "onoff"]]});
			
			levels[77].push("               ");
			levels[77].push("  sss     sss  ");
			levels[77].push(" sssss   sssss ");
			levels[77].push("sssssss sssssss");
			levels[77].push("sssssssssssssss");
			levels[77].push("sssssssssssssss");
			levels[77].push("sssssssssssssss");
			levels[77].push("sssssssssssssss");
			levels[77].push(" sssssssssssss ");
			levels[77].push("  sssssssssss  ");
			levels[77].push("   sssssssss   ");
			levels[77].push("    sssssss  t ");
			levels[77].push("     sssss  ttt");
			levels[77].push("      sss   txt");
			levels[77].push("       s    ttt");
			levels[77].push([7, 14]);
			levels[77].push({});
			levels[77].push({sw79: [13, 12, 14, 13], sw711: [3, 1, 11, 1], sw611: [0, 5, 14, 5], sw811: [6, 3, 8, 3], sw78: [3, 10, 13, 2], sw76: [11, 10, 12, 9], sw74: [7, 7, 7, 7]});
			
			levels[78].push("               ");
			levels[78].push("   tttlttt     ");
			levels[78].push("   ttt   tt ttt");
			levels[78].push("   htt   ttltxt");
			levels[78].push("     ttt  ttttt");
			levels[78].push("      ttttt    ");
			levels[78].push("thtt     ttt   ");
			levels[78].push("tttt       ttt ");
			levels[78].push(" t ttt     rtt ");
			levels[78].push("tt  ttt      t ");
			levels[78].push("tttt  tttttt tt");
			levels[78].push("tttt  ttttht tt");
			levels[78].push("   ttt   tttttt");
			levels[78].push("   thtl        ");
			levels[78].push("   tttl        ");
			levels[78].push([4, 14]);
			levels[78].push({sw33: [[6, 1, "onoff"]], sw16: [[11, 8, "onoff"]], sw1011: [[6, 14, "onoff"], [6, 13, "onoff"]], sw413: [[11, 3, "onoff"]]});
			
			levels[79].push("tt s  ttt  s tt");
			levels[79].push("te t  txt  t et");
			levels[79].push(" u t  ttt  t u ");
			levels[79].push("httt   u   ttth");
			levels[79].push("               ");
			levels[79].push("       t       ");
			levels[79].push("ttt   ttt   ttt");
			levels[79].push("tstl tt tt rtst");
			levels[79].push("ttt   ttt   ttt");
			levels[79].push("       t       ");
			levels[79].push("               ");
			levels[79].push("tttt       ttth");
			levels[79].push(" u t  tst  t u ");
			levels[79].push("te t  ttt  t tt");
			levels[79].push("tt s  ttt  s tt");
			levels[79].push([7, 14]);
			levels[79].push({sw11: [[1, 2, "onoff"]], sw131: [[13, 2, "onoff"]], sw03: [[3, 7, "onoff"]], sw143: [[7, 3, "onoff"]], sw1411: [[11, 7, "onoff"]], sw113: [[1, 12, "onoff"], [13, 12, "onoff"]]});
			levels[79].push({sw30: [13, 0, 14, 0], sw110: [12, 6, 14, 8], sw17: [6, 0, 8, 2], sw137: [0, 8, 2, 6], sw712: [0, 14, 0, 13], sw1114: [0, 0, 1, 0], sw314: [14, 13, 14, 14]});
			
			levels[80].push("     tttttttttt");
			levels[80].push("     t   t t  w");
			levels[80].push("tttttt   t t  w");
			levels[80].push("t  wwtt  tttt t");
			levels[80].push("e    rt    tt t");
			levels[80].push("tet   ttw  et w");
			levels[80].push(" ww   ttt     t");
			levels[80].push(" ww           e");
			levels[80].push(" tttttt wtwtwwt");
			levels[80].push("  t  ttmtwt    ");
			levels[80].push("tttttthtt t    ");
			levels[80].push("ttt       t rt ");
			levels[80].push("     tttl t tt ");
			levels[80].push("     txttttttt ");
			levels[80].push("     ttt       ");
			levels[80].push([9, 0]);
			levels[80].push({sw04: [[7, 9, "off"]], sw15: [[8, 12, "onoff"]], sw115: [[8, 12, "off"]], sw147: [[5, 4, "onoff"]], sw610: [[12, 11, "onoff"]]}); /*Mixed (20)*/
			
			levels[81].push("                    ");
			levels[81].push("  s    s    s   tst ");
			levels[81].push(" sts  sts  sts  sxs ");
			levels[81].push("  s    s    s   tst ");
			levels[81].push("                 t  ");
			levels[81].push("                    ");
			levels[81].push("  s    s    s    s  ");
			levels[81].push(" sts  sts  sts  sts ");
			levels[81].push("  s    s    s    s  ");
			levels[81].push("                    ");
			levels[81].push("                    ");
			levels[81].push("  s   tst   s    s  ");
			levels[81].push(" sts  sts  sts  sts ");
			levels[81].push("  s   tst   s    s  ");
			levels[81].push("       t            ");
			levels[81].push("                    ");
			levels[81].push("  s    s    s    s  ");
			levels[81].push(" sts  sts  sts  sts ");
			levels[81].push("  s    s    s    s  ");
			levels[81].push("                    ");
			levels[81].push([7, 14]);
			levels[81].push({});
			levels[81].push({sw21: [16, 2, 17, 1], sw71: [1, 2, 2, 1], sw121: [6, 2, 7, 1], sw171: [11, 2, 12, 1], sw12: [1, 7, 2, 8], sw32: [2, 16, 3, 17], sw62: [6, 7, 7, 8], sw82: [7, 16, 8, 17], sw112: [11, 7, 12, 8], sw132: [12, 16, 13, 17], sw162: [16, 7, 17, 8], sw182: [17, 16, 18, 17], sw23: [7, 3, 8, 2], sw73: [12, 3, 13, 2], sw123: [17, 3, 18, 2], sw173: [2, 3, 3, 2], sw26: [16, 7, 17, 6], sw76: [1, 7, 2, 6], sw126: [6, 7, 7, 6], sw176: [11, 7, 12, 6], sw17: [1, 12, 2, 13], sw37: [2, 1, 3, 2], sw67: [6, 12, 7, 13], sw87: [7, 1, 8, 2], sw117: [11, 12, 12, 13], sw137: [12, 1, 13, 2], sw167: [16, 12, 17, 13], sw187: [17, 1, 18, 2], sw28: [7, 8, 8, 7], sw78: [12, 8, 13, 7], sw128: [17, 8, 18, 7], sw178: [2, 8, 3, 7], sw211: [16, 12, 17, 11], sw711: [1, 12, 2, 11], sw1211: [6, 12, 7, 11], sw1711: [11, 12, 12, 11], sw312: [2, 6, 3, 7], sw612: [6, 17, 7, 18], sw812: [7, 6, 8, 7], sw1112: [11, 17, 12, 18], sw1312: [12, 6, 13, 7], sw1612: [16, 17, 17, 18], sw1812: [17, 6, 18, 7], sw213: [7, 13, 8, 12], sw713: [12, 13, 13, 12], sw1213: [17, 13, 18, 12], sw1713: [2, 13, 3, 12], sw216: [16, 17, 17, 16], sw716: [1, 17, 2, 16], sw1216: [6, 17, 7, 16], sw1716: [11, 17, 12, 16], sw317: [2, 11, 3, 12], sw617: [6, 2, 7, 3], sw817: [7, 11, 8, 12], sw1117: [11, 2, 12, 3], sw1317: [12, 11, 13, 12], sw1617: [16, 2, 17, 3], sw1817: [17, 11, 18, 12], sw218: [7, 18, 8, 17], sw718: [12, 18, 13, 17], sw1218: [17, 18, 18, 17], sw1718: [2, 18, 3, 17]});
			
			levels[82].push(" s         ht       ");
			levels[82].push(" t       ttt        ");
			levels[82].push(" u t    wttt        ");
			levels[82].push(" d     tttt         ");
			levels[82].push(" t    wtttt         ");
			levels[82].push("ttt   uutt          ");
			levels[82].push(" h  ttwwuu         t");
			levels[82].push("   t  wwwwww      tt");
			levels[82].push("  ttt wwwwttww   ttt");
			levels[82].push(" tttt  wwwttwwe ttte");
			levels[82].push("ttxtt  eeeehtww ttt ");
			levels[82].push("ttttt  eeeeethw tte ");
			levels[82].push(" tttt etwhtettt ttht");
			levels[82].push("  tt  twhwthwt   ttt");
			levels[82].push("   t thtttte      et");
			levels[82].push("    sbtt           s");
			levels[82].push("        tt          ");
			levels[82].push("      tttt          ");
			levels[82].push("        tht         ");
			levels[82].push("         tts        ");
			levels[82].push([19, 6]);
			levels[82].push({sw110: [[6, 5, "onoff"], [7, 5, "onoff"], [8, 6, "onoff"], [9, 6, "onoff"]], sw918: [[1, 2, "onoff"]], sw16: [[1, 3, "onoff"]], sw149: [[5, 15, "off"]], sw199: [[5, 15, "off"]], sw710: [[5, 15, "off"]], sw810: [[5, 15, "off"]], sw910: [[5, 15, "off"]], sw1010: [[5, 15, "off"]], sw1110: [[5, 15, "off"]], sw711: [[5, 15, "off"]], sw811: [[5, 15, "off"]], sw911: [[5, 15, "off"]], sw1011: [[5, 15, "off"]], sw1111: [[5, 15, "off"]], sw1311: [[5, 15, "off"]], sw1811: [[5, 15, "off"]], sw612: [[5, 15, "off"]], sw912: [[5, 15, "off"]], sw1112: [[5, 15, "off"]], sw1812: [[5, 15, "off"]], sw813: [[5, 15, "off"]], sw1113: [[5, 15, "off"]], sw614: [[5, 15, "off"]], sw1114: [[5, 15, "off"]], sw1814: [[5, 15, "off"]]});
			levels[82].push({sw10: [3, 7, 3, 14], sw415: [6, 17, 7, 17], sw1915: [8, 4, 9, 3], sw1119: [1, 4, 2, 5]});
			
			levels[83].push("wwwwwwwwwwww hwwwwwh");
			levels[83].push("wwwwwwwwwwww wwwwwww");
			levels[83].push("wwtwwwwwwwtw whwhhwh");
			levels[83].push("  u       t  wwwwwww");
			levels[83].push("  bt  ttt t  wwwwwww");
			levels[83].push("  rt  tht ttttwwhwww");
			levels[83].push("  d   ttt t  wwwwwww");
			levels[83].push("wwwwww t ttt        ");
			levels[83].push("wxxxxw ttttttttth   ");
			levels[83].push("wwwwww t ttt t      ");
			levels[83].push("       t     t      ");
			levels[83].push("ewwwwwwte  tttt wwww");
			levels[83].push("wwwwwwwww  ttttlwwhw");
			levels[83].push("wwwwwwwww  tttt wwww");
			levels[83].push("wwwwwwwww  tttt wwww");
			levels[83].push("wwwwwwwww    u  hwww");
			levels[83].push("wwwwwwwww  wwww hwwh");
			levels[83].push("wwwwwwwww  wwww wwww");
			levels[83].push("wwwwwwwww  whww wwww");
			levels[83].push("ewwwwwwwe  wwww hhhw");
			levels[83].push([10, 8]);
			levels[83].push({sw130: [[2, 6, "on"], [2, 4, "off"]], sw190: [[13, 15, "onoff"]], sw142: [[2, 4, "off"], [2, 6, "onoff"]],
				sw162: [[2, 4, "off"]], sw172: [[2, 4, "off"], [2, 5, "onoff"]], sw192: [[13, 15, "off"]], sw75: [[2, 3, "off"], [2, 4, "off"], [2, 5, "off"], [2, 6, "off"]],
				sw165: [[2, 5, "onoff"], [2, 6, "onoff"]], sw168: [[2, 3, "off"], [2, 4, "off"], [2, 5, "off"], [2, 6, "off"]],
				sw811: [[2, 5, "onoff"]], sw1812: [[2, 4, "off"], [2, 5, "onoff"], [2, 6, "onoff"]],
				sw019: [[2, 3, "onoff"], [2, 4, "onoff"], [2, 5, "onoff"], [2, 6, "onoff"]],
				sw1615: [[2, 4, "on"]], sw1616: [[2, 5, "on"]], sw1916: [],
				sw011: [[2, 3, "onoff"], [2, 5, "onoff"]],
				sw1218: [[15, 12, "onoff"]], sw819: [[2, 3, "on"]], sw1819: [[2, 4, "onoff"], [2, 5, "onoff"]],
				sw1719: [[2, 4, "onoff"], [2, 6, "onoff"]], sw1619: [[2, 6, "onoff"]]});
			
			levels[84].push("                    ");
			levels[84].push("       j     j      ");
			levels[84].push("fff     j   j    fff");
			levels[84].push("fxfrf    j j   ffftf");
			levels[84].push("fttrfff   j  ffftttf");
			levels[84].push("    thff    ffhtthtf");
			levels[84].push("fttssttff  ffttssttf");
			levels[84].push("fttsstttf  ftttssttf");
			levels[84].push("ffhtthttfffftthtthff");
			levels[84].push(" fttttttteetttttttf ");
			levels[84].push(" fftettttttttttettf ");
			levels[84].push("  ftettttttttttetf  ");
			levels[84].push("  hffthttttttttffh  ");
			levels[84].push("    ffffffffffff    ");
			levels[84].push("       tttttt       ");
			levels[84].push("     tttt  tttt     ");
			levels[84].push("    htttt  tttth    ");
			levels[84].push("   fftttt  ttttff   ");
			levels[84].push("  sffffe    effffs  ");
			levels[84].push("                    ");
			levels[84].push([10, 14]);
			levels[84].push({sw99: [[3, 3, "onoff"]], sw212: [[3, 4, "onoff"]], sw55: [], sw28: [], sw58: [], sw145: [], sw175: [], sw148: [], sw178: [], sw410: [], sw411: [], sw1510: [], sw1511: [], sw718: [], sw1218: [], sw416: [], sw1516: [], sw109: [], sw612: [], sw1712: []});
			levels[84].push({});
			
			levels[85].push("ttt t  t  t  t  t  t");
			levels[85].push("tttttttttttttttttttt");
			levels[85].push("ttt t  t  t  t  t  t");
			levels[85].push(" t ttttttttttttttttt");
			levels[85].push(" t  t  t  t  t  t  t");
			levels[85].push(" ttttttttttttttttttt");
			levels[85].push(" t  tttttttt t  t  t");
			levels[85].push(" ttt  ttt  t t  tttt");
			levels[85].push("  tt t   ttttttttttt");
			levels[85].push(" ttt t ttht  t tt  t");
			levels[85].push("ttt tt tttttt  ttttt");
			levels[85].push("ttt t t  t  t t tttt");
			levels[85].push("t tttttttttttttttttt");
			levels[85].push("t tt  tt    t t    t");
			levels[85].push("t   ttttttt u  ttttt");
			levels[85].push("tttt  t   t t t  t  ");
			levels[85].push("tttttttt tt ttttttt ");
			levels[85].push("t  tt  t tt tttttttt");
			levels[85].push("t  tt  t t  ttt  txt");
			levels[85].push("ttttttttttttt    ttt");
			levels[85].push([1, 1]);
			levels[85].push({sw99: [[12, 14, "on"]]});
			
			levels[86].push("                    ");
			levels[86].push("    ttt     ttstt   ");
			levels[86].push("  ttt       tttt    ");
			levels[86].push("                    ");
			levels[86].push("tttttttt            ");
			levels[86].push("et    tt ttttltrtt  ");
			levels[86].push("     tst txt     t  ");
			levels[86].push("    ttt  ttt     t  ");
			levels[86].push("  htt    ud      t  ");
			levels[86].push("tttttttt ttltrtltt  ");
			levels[86].push("  rtt et            ");
			levels[86].push("   tt               ");
			levels[86].push("   tt  tttttsttttt  ");
			levels[86].push("   tt  ht   t   th  ");
			levels[86].push("   tt  tt   t   tt  ");
			levels[86].push("   tt  tttethttttt  ");
			levels[86].push("   tt  tt   t  ttt  ");
			levels[86].push("  htt  tt   e  ttt  ");
			levels[86].push("  ttt  tttttt   tt  ");
			levels[86].push(" ttttlrttttttttttt  ");
			levels[86].push([1, 19]);
			levels[86].push({sw05: [[5, 19, "onoff"], [6, 19, "onoff"]], sw28: [[11, 9, "onoff"]], sw610: [[2, 10, "onoff"]], sw713: [[13, 9, "onoff"]], sw1713: [[15, 5, "onoff"]], sw1015: [[9, 8, "onoff"]], sw1215: [[15, 9, "onoff"]], sw217: [[13, 5, "onoff"]], sw1217: [[10, 8, "onoff"]]});
			levels[86].push({sw141: [17, 5, 17, 7], sw66: [6, 4, 7, 19], sw1212: [16, 1, 15, 2]});
			
			levels[87].push("     ttttttttt      ");
			levels[87].push("    t         t     ");
			levels[87].push("   ttttttttstsht    ");
			levels[87].push(" tlu        ttt t   ");
			levels[87].push(" drt          t  t  ");
			levels[87].push("ttl               t ");
			levels[87].push("sttt              t ");
			levels[87].push("ttttttetetet      t ");
			levels[87].push(" ttttttttttttt   t  ");
			levels[87].push("  t  ttetettttt t   ");
			levels[87].push("   t       ttttt    ");
			levels[87].push("   t         ttt    ");
			levels[87].push("    t        tt     ");
			levels[87].push("    tts      tt     ");
			levels[87].push("     ttttttttt      ");
			levels[87].push("s     ttttt t       ");
			levels[87].push("t s   t     t   d   ");
			levels[87].push("t t    t   t   ttt  ");
			levels[87].push("t t     t t    txt  ");
			levels[87].push("t t      t     ttt  ");
			levels[87].push([2, 19]);
			levels[87].push({sw142: [[16, 16, "onoff"]], sw67: [[2, 3, "off"], [2, 4, "off"], [3, 3, "on"], [1, 4, "on"]], sw79: [[3, 3, "off"], [1, 4, "off"]], sw87: [], sw99: [[2, 3, "on"], [2, 4, "on"], [2, 5, "on"], [1, 4, "off"]], sw107: [[2, 3, "on"], [1, 4, "on"], [2, 4, "off"]]});
			levels[87].push({sw112: [2, 19, 2, 17], sw132: [0, 19, 0, 17], sw06: [9, 0, 12, 0], sw613: [14, 9, 14, 11], sw015: [15, 18, 17, 18], sw216: [6, 16, 12, 16]});
			
			levels[88].push(" tttttttttstttttttt ");
			levels[88].push("te                et");
			levels[88].push("t  tttttttttttttt  t");
			levels[88].push("t tt            tt t");
			levels[88].push("t t  tttttttttt  t t");
			levels[88].push("t t tt        et t t");
			levels[88].push("t t t  tttstt  t t t");
			levels[88].push("t t t tt    et t t t");
			levels[88].push("t t t t  dd  t t t t");
			levels[88].push("t t s t rssl t s s t");
			levels[88].push("t t t t rssl t t t t");
			levels[88].push("t t t t  uu  t t t t");
			levels[88].push("t t t te    tt t t t");
			levels[88].push("t t t  tttstt  t t t");
			levels[88].push("t t te        tt t t");
			levels[88].push("e t  tttttttttt  t t");
			levels[88].push("                tt t");
			levels[88].push("ttt ttttttttttttt  e");
			levels[88].push("txtl              tt");
			levels[88].push("ttt etttttstttttttt ");
			levels[88].push([10, 19]);
			levels[88].push({sw11: [[10, 8, "onoff"], [11, 9, "onoff"], [8, 10, "onoff"], [9, 11, "onoff"]], sw145: [[10, 8, "onoff"], [11, 9, "onoff"]], sw127: [[3, 18, "off"], [8, 9, "off"], [9, 8, "off"], [11, 10, "off"], [10, 11, "off"]], sw712: [[8, 9, "on"], [9, 8, "on"], [11, 10, "on"], [10, 11, "on"]], sw514: [[8, 9, "onoff"], [9, 8, "onoff"]], sw015: [[3, 18, "on"]], sw1917: [[10, 8, "off"], [11, 9, "off"], [8, 10, "off"], [9, 11, "off"]], sw181: [], sw419: []});
			levels[88].push({sw100: [9, 4, 10, 15], sw106: [10, 19, 12, 19], sw49: [6, 9, 13, 9], sw159: [14, 2, 7, 17], sw179: [9, 9, 10, 10], sw1013: [9, 4, 10, 15], sw1019: [0, 9, 19, 9], sw1010: [0, 17, 2, 19], sw109: [0, 17, 2, 19], sw99: [0, 17, 2, 19], sw910: [0, 17, 2, 19]});
			
			levels[89].push("                    ");
			levels[89].push("                    ");
			levels[89].push("          jdj       ");
			levels[89].push("     jjjjjjjjj      ");
			levels[89].push("     jjhjjj jjjjjj  ");
			levels[89].push("   rjj          jj  ");
			levels[89].push("  jjjj jjjjj j  jj  ");
			levels[89].push(" jj    jje jj   jjj ");
			levels[89].push(" rj   jjj  j     rjh");
			levels[89].push(" j    jj   j      j ");
			levels[89].push(" jj   j    j    jjj ");
			levels[89].push(" jj   jj   j    jj  ");
			levels[89].push("  j   jj   j    jjh ");
			levels[89].push(" jj    jjj jj    jj ");
			levels[89].push(" jh     jjjjjjjjjjj ");
			levels[89].push(" jjj                ");
			levels[89].push("  jjj               ");
			levels[89].push("   jjj      jjj  jjj");
			levels[89].push("    jjjjjjjjjjjjljxj");
			levels[89].push("     jjj    jjj  jjj");
			levels[89].push([11, 12]);
			levels[89].push({sw74: [[17, 8, "onoff"]], sw97: [[11, 2, "onoff"]], sw1812: [[3, 5, "onoff"]], sw214: [[16, 18, "onoff"]], sw198: [[1, 8, "onoff"]]});
			
			levels[90].push("        fffff       ");
			levels[90].push("       fetttef      ");
			levels[90].push("       fthtttf      ");
			levels[90].push("        ftttf       ");
			levels[90].push("    fff ftttf fff   ");
			levels[90].push("   ftttfutttuftttf  ");
			levels[90].push("  fttttet   ettettf ");
			levels[90].push("  fhtetet h ettttsf ");
			levels[90].push("   ffffft   efffff  ");
			levels[90].push("        deee        ");
			levels[90].push("      fftttteff     ");
			levels[90].push("     fettfwffttff   ");
			levels[90].push("     fettfw  fthf   ");
			levels[90].push("      fff w   fff   ");
			levels[90].push("          w         ");
			levels[90].push("          w         ");
			levels[90].push("          w         ");
			levels[90].push("       jjjjjjj      ");
			levels[90].push("        jjxjj       ");
			levels[90].push("         jjj        ");
			levels[90].push([10, 1]);
			levels[90].push({sw81: [[8, 5, "off"], [12, 5, "off"], [8, 9, "off"]], sw121: [[8, 5, "off"], [12, 5, "off"], [8, 9, "off"]], sw76: [[8, 5, "off"], [12, 5, "off"], [8, 9, "off"]], sw126: [[8, 5, "off"], [12, 5, "off"], [8, 9, "off"]], sw156: [[8, 5, "off"], [12, 5, "off"], [8, 9, "off"]], sw57: [[8, 5, "off"], [12, 5, "off"], [8, 9, "off"]], sw77: [[8, 5, "off"], [12, 5, "off"], [8, 9, "off"]], sw127: [[8, 5, "off"], [12, 5, "off"], [8, 9, "off"]], sw128: [[8, 5, "off"], [12, 5, "off"], [8, 9, "off"]], sw99: [[8, 5, "off"], [12, 5, "off"], [8, 9, "off"]], sw109: [[8, 5, "off"], [12, 5, "off"], [8, 9, "off"]], sw119: [[8, 5, "off"], [12, 5, "off"], [8, 9, "off"]], sw1210: [[8, 5, "off"], [12, 5, "off"], [8, 9, "off"]], sw611: [[8, 5, "off"], [12, 5, "off"], [8, 9, "off"]], sw612: [[8, 5, "off"], [12, 5, "off"], [8, 9, "off"]], sw92: [[8, 5, "on"]], sw37: [[8, 9, "on"]], sw1512: [[12, 5, "on"]], sw107: []});
			levels[90].push({sw177: [7, 17, 13, 7]});
			
			levels[91].push("  ttttttt   httttth ");
			levels[91].push("  et   tttttttetttt ");
			levels[91].push("ttth      ttt     t ");
			levels[91].push("ttt              tt ");
			levels[91].push("  t             tet ");
			levels[91].push("  t  rtrtttrtl htt  ");
			levels[91].push("  t  ttttrtttt  tett");
			levels[91].push(" ttt d       u   ttt");
			levels[91].push(" tst t    tt t     t");
			levels[91].push(" ttt ttl ttt d    tt");
			levels[91].push("     rtt txt t    tt");
			levels[91].push("ttt   h  ttt tl ett ");
			levels[91].push("ttt      u   tt tttt");
			levels[91].push("  t     tttdttt   tt");
			levels[91].push("  t     tutttut   tt");
			levels[91].push(" ttt    tt        tt");
			levels[91].push(" tt               tt");
			levels[91].push("tth     ttttt    htt");
			levels[91].push("thtttttttt thttttttt");
			levels[91].push("tt               tth");
			levels[91].push([3, 15]);
			levels[91].push({sw120: [[5, 10, "onoff"]], sw180: [[7, 5, "onoff"]], sw141: [[13, 7, "onoff"]], sw21: [[7, 9, "onoff"]], sw32: [[11, 5, "onoff"]], sw174: [[13, 9, "onoff"]], sw1611: [[13, 5, "onoff"]], sw155: [[11, 13, "onoff"]], sw176: [[5, 5, "onoff"]], sw611: [[5, 7, "onoff"]], sw217: [[9, 6, "onoff"]], sw1717: [[14, 11, "onoff"]], sw118: [[9, 12, "onoff"]], sw1218: [[9, 14, "onoff"]], sw1919: [[13, 14, "onoff"]]});
			levels[91].push({sw28: [5, 9, 7, 10]});
			
			levels[92].push("etttttttttttt   tttt");
			levels[92].push("   ttt     tt   t  t");
			levels[92].push("   ttttt   tt   t  t");
			levels[92].push("tttt   t   t httt  t");
			levels[92].push("t      t   ttt     t");
			levels[92].push("t   tttt  tttttltwwt");
			levels[92].push("u   t  httt      wwt");
			levels[92].push("tt  t  t  t tttt   u");
			levels[92].push("t ttt  u  ttt tt   d");
			levels[92].push("t tt  tt  ttt tttt t");
			levels[92].push("t htttttt  u  tttttt");
			levels[92].push("t    ttte  t     ttt");
			levels[92].push("ht        rtl       ");
			levels[92].push("     s   tttttttt   ");
			levels[92].push(" tww t   tt     t   ");
			levels[92].push(" tww t   tttt   t   ");
			levels[92].push(" t   tww   tt   t   ");
			levels[92].push("tt tt wwt  tt   tttt");
			levels[92].push("ttwtttwww       ttxt");
			levels[92].push("ttwtttwww        ttt");
			levels[92].push([0, 19]);
			levels[92].push({sw00: [[15, 5, "onoff"]], sw133: [[11, 10, "onoff"]], sw76: [[19, 7, "onoff"], [19, 8, "onoff"]], sw210: [[10, 12, "onoff"], [12, 12, "onoff"]], sw811: [[7, 8, "onoff"]], sw012: [[0, 6, "onoff"]]});
			levels[92].push({sw513: [1, 12, 1, 7]});
			
			levels[93].push("              e     ");
			levels[93].push("   sssss     ttt    ");
			levels[93].push("  sssssss   tthtt   ");
			levels[93].push(" sss   sss tt t tt  ");
			levels[93].push(" ss     ss t  t  t  ");
			levels[93].push(" ss     ss    h     ");
			levels[93].push(" sss   sss    t     ");
			levels[93].push("  sssssss     t     ");
			levels[93].push("   sssss      t     ");
			levels[93].push("     s        t     ");
			levels[93].push("     s        u     ");
			levels[93].push("     s     dtttth   ");
			levels[93].push("     s    ttt   tt  ");
			levels[93].push("     s    tt ttt ht ");
			levels[93].push("     s    tt txt tt ");
			levels[93].push("  sssssss tt ttt tt ");
			levels[93].push("     s    ttt u ttt ");
			levels[93].push("     s     ttttttl  ");
			levels[93].push("     s     rttttt   ");
			levels[93].push("     s              ");
			levels[93].push([5, 19]);
			levels[93].push({sw140: [[11, 18, "onoff"]], sw142: [[11, 11, "onoff"]], sw145: [[14, 10, "onoff"]], sw1611: [[17, 17, "onoff"]], sw1713: [[14, 16, "onoff"]]});
			levels[93].push({sw57: [3, 1, 7, 1], sw511: [5, 12, 5, 10], sw518: [2, 15, 8, 15], sw515: [11, 4, 17, 4]});
			
			levels[94].push("            wwwww   ");
			levels[94].push("           wwxww    ");
			levels[94].push("          wwwww     ");
			levels[94].push("          ww        ");
			levels[94].push("    eww      wwwwww ");
			levels[94].push("   wwwww    wwwwws  ");
			levels[94].push("  wwwwwee  wweeww   ");
			levels[94].push(" wwwwwwww  wweew    ");
			levels[94].push(" wwwwwwwwwwwwwww    ");
			levels[94].push("wwwwwwwwwwwwwwww    ");
			levels[94].push("wwwwwwwwwwwwwwwww   ");
			levels[94].push("wwwwwwwwwwwwwwwwww  ");
			levels[94].push("wewwwwwwwwwwwwwwewww");
			levels[94].push(" wwweewwwwwwwwwwwwww");
			levels[94].push("  wwwwwwwwwwwwwwwww ");
			levels[94].push("  wwwwwwwwwwwwwweww ");
			levels[94].push("   wwewwwwwwwwwwww  ");
			levels[94].push("    wwwwwwwwwwwww   ");
			levels[94].push("     wwwwwwwwwew    ");
			levels[94].push("      wwe  www      ");
			levels[94].push([4, 4]);
			levels[94].push({sw76: [], sw86: [], sw44: [], sw136: [], sw146: [], sw137: [], sw147: [], sw112: [], sw413: [], sw513: [], sw1612: [], sw516: [], sw1418: [], sw819: [], sw1615: []});
			levels[94].push({sw175: [10, 3, 11, 2]});
			
			levels[95].push("      ttttttt       ");
			levels[95].push("     ee     t       ");
			levels[95].push("     tt     t       ");
			levels[95].push("   etlu     t  ttt  ");
			levels[95].push("   etlmttt  t  ttts ");
			levels[95].push("     tt  t  t  t    ");
			levels[95].push("     ee  t  tttt    ");
			levels[95].push("         u       d  ");
			levels[95].push("ttt tt   t  tt  fff ");
			levels[95].push("tts tt   t  tt rfxfl");
			levels[95].push("ttt tttthhhttt  fff ");
			levels[95].push("        t t      u  ");
			levels[95].push("        t t   ttt   ");
			levels[95].push("ttttttttl rtttttt   ");
			levels[95].push("tttt            t s ");
			levels[95].push("  tt       tttttt tt");
			levels[95].push(" tth  tttt tt     tt");
			levels[95].push(" tt   t  t tttttth t");
			levels[95].push(" tt   t  t  tt   ttt");
			levels[95].push(" ttlttt  s  tt   ttt");
			levels[95].push([0, 10]);
			levels[95].push({sw51: [[5, 4, "off"]], sw61: [[6, 3, "on"]], sw33: [[5, 3, "on"]], sw34: [[5, 4, "off"]], sw56: [[5, 4, "on"]], sw66: [[5, 3, "on"]], sw810: [[8, 13, "on"], [9, 7, "off"], [10, 13, "off"]], sw910: [[8, 13, "off"], [9, 7, "on"], [10, 13, "off"]], sw1010: [[8, 13, "off"], [9, 7, "off"], [10, 13, "on"]], sw316: [[3, 19, "onoff"]], sw1717: [[15, 9, "onoff"], [17, 7, "onoff"], [19, 9, "onoff"], [17, 11, "onoff"]]});
			levels[95].push({sw184: [16, 8, 18, 10], sw29: [4, 8, 13, 8], sw1814: [0, 8, 2, 10], sw919: [0, 8, 2, 10]});
			
			levels[96].push("    jj   jjjjj jjjj ");
			levels[96].push("jjjjjj   jjjjjjj    ");
			levels[96].push("jjjjjjjjjj   jjj jjj");
			levels[96].push("  jj             jxj");
			levels[96].push("  jj         jjj jjj");
			levels[96].push("  jj    jjjjjjjj ju ");
			levels[96].push("  jjj jjj   j jj j  ");
			levels[96].push("    jjjjj   jjjjjjjj");
			levels[96].push("    jjj     jj   j j");
			levels[96].push("            jj   j j");
			levels[96].push("  jjj         jjjjjj");
			levels[96].push("jjjjjj  jjjjjjjj j  ");
			levels[96].push("jjj jjj jj       j  ");
			levels[96].push("j    jjjjj   jj  j  ");
			levels[96].push("j jjjj       jj  j  ");
			levels[96].push("jjj     j    jjjjjj ");
			levels[96].push("  j    hjj   j    jj");
			levels[96].push("  jjjjjjjjjjjjj   jj");
			levels[96].push("            jjjjjjjj");
			levels[96].push("            jjj     ");
			levels[96].push([18, 0]);
			levels[96].push({sw716: [[18, 5, "onoff"]]});
			
			levels[97].push("       jjjjjj       ");
			levels[97].push("    hjjhjjhjjhjj    ");
			levels[97].push("  jjjjjjjjjjjjjjjj  ");
			levels[97].push("  jjjj   jj   jjhj  ");
			levels[97].push(" jjhj jjj  jjj jjjj ");
			levels[97].push(" ejjj jxj  jxj jjjj ");
			levels[97].push(" jjjj jxjlrjxjlhjjj ");
			levels[97].push("jjjhj jjj  jjj hjjhj");
			levels[97].push("jejjjj   jj   jjjjjj");
			levels[97].push("jjojjjjjjjjjjjjjojjj");
			levels[97].push("jjohjjhjjhjjhjjhojhj");
			levels[97].push("jeoojjjjjjjjjjjjojjj");
			levels[97].push("jjooojjjjjjjjjooojjj");
			levels[97].push(" jooooojjjjoooohjjh ");
			levels[97].push(" ejoooooooooooojjjj ");
			levels[97].push(" jjjoooooooooojjjjj ");
			levels[97].push("  jejooooooohjjhjj  ");
			levels[97].push("  jjjejjjjjjjjjjjj  ");
			levels[97].push("    jjjejjjjjjjj    ");
			levels[97].push("       jjjjjh       ");
			levels[97].push([9, 19]);
			levels[97].push({sw41: [], sw71: [], sw101: [], sw156: [], sw131: [], sw34: [], sw15: [], sw37: [[9, 6, "onoff"], [10, 6, "onoff"]], sw18: [], sw157: [], sw187: [], sw163: [[14, 6, "onoff"]], sw310: [], sw610: [], sw910: [], sw1210: [], sw1510: [], sw1810: [], sw111: [], sw1513: [], sw1813: [], sw316: [], sw1216: [], sw1516: [], sw517: [], sw718: [], sw1219: []});
			
			levels[98].push(" hlrh      ttttttttt");
			levels[98].push(" u  u       ttt    t");
			levels[98].push(" d ttt ttt   tu   tt");
			levels[98].push(" h txt ttt    d  ttt");
			levels[98].push(" u ttt   t    hhlrtt");
			levels[98].push(" d       t tlrhh   t");
			levels[98].push(" httt    t tt  u   t");
			levels[98].push("    tttttt tt  d  tt");
			levels[98].push("    ttttlrttt  ttttt");
			levels[98].push("ttt       ttttttttt ");
			levels[98].push("ttttttt     u       ");
			levels[98].push("t     t     d       ");
			levels[98].push("tlrhh t    rhh  tttt");
			levels[98].push("   hhttt   rhhlrtttt");
			levels[98].push("   uu  t    uu  t   ");
			levels[98].push("   d   t    d  ttt  ");
			levels[98].push("   tttttlttttttttt  ");
			levels[98].push("   tt          tt   ");
			levels[98].push("   tt               ");
			levels[98].push("                    ");
			levels[98].push([7, 16]);
			levels[98].push({sw10: [[2, 0, "onoff"], [3, 0, "onoff"]], sw40: [[4, 1, "onoff"]], sw13: [[1, 1, "onoff"], [1, 2, "onoff"]], sw144: [[16, 4, "onoff"], [17, 4, "onoff"]], sw154: [[12, 5, "onoff"], [13, 5, "onoff"]], sw145: [[8, 8, "onoff"], [9, 8, "onoff"]], sw155: [[14, 2, "onoff"], [14, 3, "onoff"]], sw16: [[1, 4, "onoff"], [1, 5, "onoff"]], sw312: [[4, 14, "onoff"]], sw412: [[8, 16, "onoff"], [12, 14, "onoff"], [12, 15, "onoff"]], sw1212: [[15, 6, "onoff"], [15, 7, "onoff"]], sw1312: [[12, 10, "onoff"], [12, 11, "onoff"], [13, 14, "onoff"]], sw1213: [[14, 13, "onoff"], [15, 13, "onoff"]], sw1313: [[11, 12, "onoff"], [11, 13, "onoff"]], sw313: [[1, 12, "onoff"], [2, 12, "onoff"]], sw413: [[3, 14, "onoff"], [3, 15, "onoff"]]});
			
			levels[99].push("                 ttt");
			levels[99].push("ttttttttttttttttttxt");
			levels[99].push("  u   u   u      ttt");
			levels[99].push("  d   d   d       t ");
			levels[99].push("  tttttttttttt    t ");
			levels[99].push(" tttttttetttttt   t ");
			levels[99].push("tttttttttoootttt  t ");
			levels[99].push("thttttttoooothtt  t ");
			levels[99].push("ttttttttoottttttlrt ");
			levels[99].push("ttttttttootttttt  t ");
			levels[99].push("ttttttttootttttt  t "); /*B - o, white*/
			levels[99].push("ttettttoooottttt  t ");
			levels[99].push("tttttttooootttttlrt ");
			levels[99].push("ttttttttootttttt  t ");
			levels[99].push("ttttttttootttttt  t ");
			levels[99].push("ttttttttoottttttlrt ");
			levels[99].push("thttttttootttttt  t ");
			levels[99].push("ttttttttootttett  t ");
			levels[99].push(" tttttttttttttt   t ");
			levels[99].push("  tttttetttttt    t ");
			levels[99].push([7, 14]);
			levels[99].push({sw85: [[10, 2, "onoff"], [10, 3, "onoff"]], sw17: [[6, 2, "onoff"], [6, 3, "onoff"]], sw137: [[16, 8, "onoff"], [17, 8, "onoff"]], sw211: [[16, 12, "onoff"], [17, 12, "onoff"]], sw116: [[16, 15, "onoff"], [17, 15, "onoff"]], sw1317: [[16, 12, "onoff"], [17, 12, "onoff"]], sw719: [[2, 2, "onoff"], [2, 3, "onoff"]]});
			
			levels[100].push("        hlrttttttttt");
			levels[100].push(" sfff      u t   txt");
			levels[100].push("    fttt   d t   ttt");
			levels[100].push("    ffffdd h ttttuu ");
			levels[100].push("       fff      t   ");
			levels[100].push("twt     rffl    t   ");
			levels[100].push(" w        ftl   tte ");
			levels[100].push(" h wwwj w fffttl ett");
			levels[100].push(" d jwww ww  ffffl  u");
			levels[100].push(" w ww w jww   rfff d");
			levels[100].push(" jwjjwj www   tlrf h");
			levels[100].push("   j   jwww     rf u");
			levels[100].push("wwjwwwwwjwj  ddfff d");
			levels[100].push("ww wwjww    fffuu  h");
			levels[100].push("wws     dddffu     n");
			levels[100].push("       fffffu      m");
			levels[100].push("h   dtff rtt hvbhvbh");
			levels[100].push("tt rffft  uu u  n  n");
			levels[100].push("tttffu       d  m  m");
			levels[100].push("ttth      ttthlrhvbh");
			levels[100].push([0, 19]);
			levels[100].push({sw80: [[18, 3, "onoff"]], sw113: [[17, 3, "onoff"], [9, 0, "on"], [10, 0, "on"]],
				sw186: [[11, 1, "on"], [11, 2, "on"], [9, 0, "off"], [10, 0, "off"]], sw17: [[1, 8, "onoff"]],
				sw177: [[11, 1, "off"], [11, 2, "off"], [9, 0, "on"], [10, 0, "on"]],
				sw1910: [[19, 8, "onoff"], [19, 9, "onoff"]], sw1913: [[19, 12, "onoff"], [19, 11, "onoff"]],
				sw1316: [[14, 16, "on"], [15, 16, "on"]],
				sw1616: [[17, 16, "on"], [18, 16, "on"], [16, 18, "on"], [16, 17, "on"]],
				sw1916: [[19, 17, "on"], [19, 18, "on"]],
				sw1319: [[13, 17, "on"], [13, 18, "on"], [14, 19, "on"], [15, 19, "on"], [16, 17, "off"],
					[16, 18, "off"], [14, 16, "off"], [15, 16, "off"], [17, 16, "off"], [18, 16, "off"],
					[17, 19, "off"], [18, 19, "off"], [19, 17, "off"], [19, 18, "off"], [19, 14, "off"],
					[19, 15, "off"]], sw1619: [[17, 19, "on"], [18, 19, "on"], [19, 14, "on"], [19, 15, "on"]],
				sw1919: [[17, 16, "on"], [18, 16, "on"]], sw319: [[10, 17, "on"], [11, 17, "on"], [8, 5, "on"],
					[12, 6, "on"], [15, 7, "on"], [16, 10, "on"], [16, 11, "on"], [13, 12, "on"], [14, 12, "on"],
					[12, 15, "on"], [9, 16, "on"], [3, 17, "on"], [5, 18, "on"], [8, 3, "off"], [9, 3, "off"],
					[11, 5, "off"], [16, 8, "off"], [14, 9, "off"], [15, 10, "off"], [15, 13, "off"], [16, 13, "off"],
					[8, 14, "off"], [9, 14, "off"], [10, 14, "off"], [13, 14, "off"], [4, 16, "off"]],
				sw016: [[8, 5, "off"], [12, 6, "off"], [15, 7, "off"], [16, 10, "off"], [16, 11, "off"],
					[13, 12, "off"], [14, 12, "off"], [12, 15, "off"], [9, 16, "off"], [3, 17, "off"], [5, 18, "off"],
					[8, 3, "on"], [9, 3, "on"], [11, 5, "on"], [16, 8, "on"], [14, 9, "on"], [15, 10, "on"],
					[15, 13, "on"], [16, 13, "on"], [8, 14, "on"], [9, 14, "on"], [10, 14, "on"], [13, 14, "on"],
					[4, 16, "on"], [10, 17, "off"], [11, 17, "off"]]});
			levels[100].push({sw11: [0, 5, 1, 6], sw214: [10, 19, 12, 19]});
			
			levels[101].push("                    ");
			levels[101].push(" xxxxxxxxxxx   s    ");
			levels[101].push(" xxxxxxxxxx     s   ");
			levels[101].push(" xxtxxxxxx   s  s   ");
			levels[101].push(" xxxxxxxx   j s s   ");
			levels[101].push(" xxxxxxx     j sssss");
			levels[101].push(" xxxxxx   j   j s   ");
			levels[101].push(" xxxxx     jjjjj s  ");
			levels[101].push(" xxxx   eee j   j s ");
			levels[101].push(" xxx    e  e j   j  ");
			levels[101].push(" xx   w e   e j     ");
			levels[101].push(" x     w e e e j    ");
			levels[101].push("    t   w e   e     ");
			levels[101].push("   t w  ww e        ");
			levels[101].push("  t   www w e   f   ");
			levels[101].push(" t t   w   w     f  ");
			levels[101].push("t   t   w        f  ");
			levels[101].push("     t   w   f    f ");
			levels[101].push("      t       ff  f ");
			levels[101].push("       t        fff ");
			levels[101].push([3, 3]);

		/*
		   levels[].push("                    ");
		   levels[].push("                    ");
		   levels[].push("                    ");
		   levels[].push("                    ");
		   levels[].push("                    ");
		   levels[].push("                    ");
		   levels[].push("                    ");
		   levels[].push("                    ");
		   levels[].push("                    ");
		   levels[].push("                    ");
		   levels[].push("                    ");
		   levels[].push("                    ");
		   levels[].push("                    ");
		   levels[].push("                    ");
		   levels[].push("                    ");
		   levels[].push("                    ");
		   levels[].push("                    ");
		   levels[].push("                    ");
		   levels[].push("                    ");
		   levels[].push("                    ");
		   levels[].push([ , ]);
		   levels[].push({sw: [[]]});
		 levels[].push({sw: []});  SAMPLE 20x20*/

		/*levels[].push("               ");
		   levels[].push("               ");
		   levels[].push("               ");
		   levels[].push("               ");
		   levels[].push("               ");
		   levels[].push("               ");
		   levels[].push("               ");
		   levels[].push("               ");
		   levels[].push("               ");
		   levels[].push("               ");
		   levels[].push("               ");
		   levels[].push("               ");
		   levels[].push("               ");
		   levels[].push("               ");
		   levels[].push("               ");
		   levels[].push([ , ]);
		   levels[].push({});
		 levels[].push({sw: []}); 	SAMPLE 15x15*/

		}	
	}
}